//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Oct 18 12:00:20 2002 by ROOT version 3.03/06)
//      from the StreamerInfo in file prv3.root
//////////////////////////////////////////////////////////


#ifndef TRDTrackRoot_h
#define TRDTrackRoot_h

#include "TObject.h"
#include "TRefArray.h"

class TRDTrackRoot : public TObject {

public:
   int         Status;        //
   float       Coo[3];        //
   float       ErCoo[3];      //
   float       Phi;           //
   float       Theta;         //
   float       Chi2;          //
   int         NSeg;          //
   int         Pattern;       //
   TRefArray*  fTRDSegment;   //

   TRDTrackRoot();
   virtual ~TRDTrackRoot();

   ClassDef(TRDTrackRoot,1) //
};

#endif
