//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Oct 18 12:00:20 2002 by ROOT version 3.03/06)
//      from the StreamerInfo in file prv3.root
//////////////////////////////////////////////////////////


#ifndef TrTrackRoot02_h
#define TrTrackRoot02_h

#include "TObject.h"
#include "TRefArray.h"

class TrTrackRoot02 : public TObject {

public:
   int         Status;            //
   int         Pattern;           //
   int         Address;           //
   int         NHits;             //
   float       LocDBAver;         //
   int         GeaneFitDone;      //
   int         AdvancedFitDone;   //
   float       Chi2StrLine;       //
   float       Chi2Circle;        //
   float       CircleRigidity;    //
   float       Chi2FastFit;       //
   float       Rigidity;          //
   float       ErrRigidity;       //
   float       Theta;             //
   float       Phi;               //
   float       P0[3];             //
   float       GChi2;             //
   float       GRigidity;         //
   float       GErrRigidity;      //
   float       HChi2[2];          //
   float       HRigidity[2];      //
   float       HErrRigidity[2];   //
   float       HTheta[2];         //
   float       HPhi[2];           //
   float       HP0[2][3];         //
   float       FChi2MS;           //
   float       PiErrRig;          //
   float       RigidityMS;        //
   float       PiRigidity;        //
   TRefArray*  fTrRecHit;         //

   TrTrackRoot02();
   virtual ~TrTrackRoot02();

   ClassDef(TrTrackRoot02,1) //
};

#endif
