/********************************************************************
* mydict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mydict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablemydict();
extern void G__cpp_setup_inheritancemydict();
extern void G__cpp_setup_typetablemydict();
extern void G__cpp_setup_memvarmydict();
extern void G__cpp_setup_globalmydict();
extern void G__cpp_setup_memfuncmydict();
extern void G__cpp_setup_funcmydict();
extern void G__set_cpp_environmentmydict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "VCon_gbatch.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mydictLN_AMSlink;
extern G__linked_taginfo G__mydictLN_AMSContainer;
extern G__linked_taginfo G__mydictLN_VCon;
extern G__linked_taginfo G__mydictLN_VCon_gb;

/* STUB derived class for protected member access */
