   1:SEND COMMAND                  :CAN-02, C44, CCS_READ_SETPOINT_CMDS.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, Pausini, NONE
   3:SEND COMMAND                  :CAN-02, C47, CCS_ANALOG_TM_ACQUIRE.CMM, 0
   4:SEND COMMAND                  :CAN-02, C48, CCS_READ_ANALOG_TM.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, Pausini, NONE
   6:SEND COMMAND                  :CAN-02, C1E, CAB_READ_AND_RESET_ERROR_INFO.CMM, 0
   7:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, Pausini, NONE
   9:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_ENA.CMM, 0
  10:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
  11:REQUEST MESSAGE               :GEP-05, This is a request message, NONE