   2:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   1:SEND COMMAND                  :CAN-02, C72, PS_ENA_DIS_VACUUM_SENSOR_NOM_DIS.CMM, 0
   2:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE