   3:REQUEST MESSAGE               :GEP-05, NO SW de grupo_LANZAR_ADQUISICION, NONE
   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_DIS.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0

   3:REQUEST MESSAGE               :GEP-05, 35mV_LANZAR_ADQUISICION, NONE
   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE

   3:REQUEST MESSAGE               :GEP-05, 29mV_LANZAR_ADQUISICION, NONE
   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE

   3:REQUEST MESSAGE               :GEP-05, 26mV_LANZAR_ADQUISICION, NONE
   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE

   3:REQUEST MESSAGE               :GEP-05, 18mV_LANZAR_ADQUISICION, NONE
   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE

   3:REQUEST MESSAGE               :GEP-05, 13mV_LANZAR_ADQUISICION, NONE
   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE

   3:REQUEST MESSAGE               :GEP-05, 5mV_LANZAR_ADQUISICION, NONE
   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE

   3:REQUEST MESSAGE               :GEP-05, 0_plus_mV_LANZAR_ADQUISICION, NONE
   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE

   3:REQUEST MESSAGE               :GEP-05, 0mV_LANZAR_ADQUISICION, NONE
   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE