   1:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   2:SEND COMMAND                  :CAN-02, C71, PS_ENA_DIS_HT_HEATER_GROUP_RED_ENA.CMM, 0
   3:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   5:SEND COMMAND                  :CAN-02, C72, PS_ENA_DIS_VACUUM_SENSOR_RED_ENA.CMM, 0
   6:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
   7:REQUEST MESSAGE               :GEP-05, Medir Vp en CH113, NONE
   8:READ POWER SIGNAL             :DMM-01, CAB, CCS_TO_ACTIVE_L_V, IF2, NONE, VOLTS
   9:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
  10:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_RED_ENER_DIS.CMM, 0
  11:SEND COMMAND                  :CAN-02, C22, STM_READ_RED.CMM, 0
  12:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  13:SEND COMMAND                  :CAN-02, C71, PS_ENA_DIS_HT_HEATER_GROUP_RED_DIS.CMM, 0
  14:SEND COMMAND                  :CAN-02, C72, PS_ENA_DIS_VACUUM_SENSOR_RED_DIS.CMM, 0
  15:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  16:REQUEST MESSAGE               :GEP-05, Medir Vp en CH113, NONE
  17:READ POWER SIGNAL             :DMM-01, CAB, CCS_TO_ACTIVE_L_V, IF2, NONE, VOLTS
  18:REQUEST MESSAGE               :GEP-05, This is a request message, NONE