/********************************************************************
* src/ViewerGUIDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/ViewerGUIDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableViewerGUIDict();
extern void G__cpp_setup_inheritanceViewerGUIDict();
extern void G__cpp_setup_typetableViewerGUIDict();
extern void G__cpp_setup_memvarViewerGUIDict();
extern void G__cpp_setup_globalViewerGUIDict();
extern void G__cpp_setup_memfuncViewerGUIDict();
extern void G__cpp_setup_funcViewerGUIDict();
extern void G__set_cpp_environmentViewerGUIDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/calocube/TIC_TB2018/May2018_TIC/Software/CaloKagathos/AMS_CCviewer/include/ViewerGUI.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ViewerGUIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ViewerGUIDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ViewerGUIDictLN_TList;
extern G__linked_taginfo G__ViewerGUIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ViewerGUIDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ViewerGUIDictLN_TQObjSender;
extern G__linked_taginfo G__ViewerGUIDictLN_TGWindow;
extern G__linked_taginfo G__ViewerGUIDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__ViewerGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__ViewerGUIDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ViewerGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ViewerGUIDictLN_TGMainFrame;
extern G__linked_taginfo G__ViewerGUIDictLN_TCanvas;
extern G__linked_taginfo G__ViewerGUIDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__ViewerGUIDictLN_TGNumberEntry;
extern G__linked_taginfo G__ViewerGUIDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ViewerGUIDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ViewerGUIDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ViewerGUIDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ViewerGUIDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ViewerGUIDictLN_ViewerGUI;

/* STUB derived class for protected member access */
