#!/bin/sh -x

if [ "$#" -lt 0 ]
    then
    echo "$0 [args]"
    exit
fi

APP=$1

for tdr in `seq 500 523`; do
  for thr in 20 50 75 100; do
      echo ModifyStripStatus $tdr $thr
      echo ...
  done
done


