   1:SEND COMMAND                  :CAN-02, C95, CSP_AQS_CONFIGURATION_1N_DUR_MIN.CMM, 0
   2:SEND COMMAND                  :CAN-02, C95, CSP_AQS_CONFIGURATION_2N_DUR_MIN.CMM, 0
   3:SEND COMMAND                  :CAN-02, C95, CSP_AQS_CONFIGURATION_1R_DUR_MIN.CMM, 0
   4:SEND COMMAND                  :CAN-02, C95, CSP_AQS_CONFIGURATION_2R_DUR_MIN.CMM, 0
   5:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE