#!/bin/sh


cont=40
max=100
events=50000


while [ $cont -le $max ]; do

echo $cont
echo ln -s JINF_01_$cont.conf JINF_01.conf
ln -s JINF_01_$cont.conf JINF_01.conf

echo ./TakeJEPP  0 COMPLETERUN $events 1 
./TakeJEPP  0 COMPLETERUN 50000 0

echo rm -f JINF_01.conf
rm -f JINF_01.conf
sleep 10

cont=`expr $cont + 10`
echo $cont

done
