/********************************************************************
* toto.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error toto.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtabletoto();
extern void G__cpp_setup_inheritancetoto();
extern void G__cpp_setup_typetabletoto();
extern void G__cpp_setup_memvartoto();
extern void G__cpp_setup_globaltoto();
extern void G__cpp_setup_memfunctoto();
extern void G__cpp_setup_functoto();
extern void G__set_cpp_environmenttoto();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "slowgui.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__totoLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__totoLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__totoLN_TGWindow;
extern G__linked_taginfo G__totoLN_TGMainFrame;
extern G__linked_taginfo G__totoLN_ScopeDis;

/* STUB derived class for protected member access */
