   1:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, CB7, CSP_ON_OFF_CONVERTERS_CTRL_NOM_OFF.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, CB7, CSP_ON_OFF_CONVERTERS_CTRL_RED_OFF.CMM, 0
   4:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   6:SEND COMMAND                  :CAN-02, CB7, CSP_ON_OFF_CONVERTERS_MD1_OFF.CMM, 0
   7:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   8:SEND COMMAND                  :CAN-02, CB7, CSP_ON_OFF_CONVERTERS_MD2_OFF.CMM, 0
   9:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  10:SEND COMMAND                  :CAN-02, CB7, CSP_ON_OFF_CONVERTERS_MD3_OFF.CMM, 0
  11:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  12:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  13:SEND COMMAND                  :CAN-02, CB7, CSP_ON_OFF_CONVERTERS_CL1_OFF.CMM, 0
  14:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  15:SEND COMMAND                  :CAN-02, CB7, CSP_ON_OFF_CONVERTERS_CL2_OFF.CMM, 0
  16:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  17:SEND COMMAND                  :CAN-02, CB7, CSP_ON_OFF_CONVERTERS_CL3_OFF.CMM, 0
  18:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  19:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  18:E/D PS OUTPUT                 :PWS-05, BATTERY_SIMULATOR_N, DISABLE
  19:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE