   1:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE