   2:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   4:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS10_60S_NOM.CMM, 0
   5:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS10_60S_NOM.CMM, 0
   6:EXECUTE TEST SEQUENCE         :GEP-22, CSP_GET_CONFIG_AQS_RDS_N, NONE
   7:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE