   2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE CSP_MOOG VALVE DV22A 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_OPEN_V22A.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE CSP_MOOG VALVE DV22A 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_OPEN_V22A.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0


   2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE CSP_MOOG VALVE DV22B 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_OPEN_V22B.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE CSP_MOOG VALVE DV22B 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_OPEN_V22B.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0


   2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE CSP_MOOG VALVE DV22C 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_OPEN_V22C.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE CSP_MOOG VALVE DV22C 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_OPEN_V22C.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE CSP_MOOG VALVE DV22D 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_OPEN_V22D.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE CSP_MOOG VALVE DV22D 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_OPEN_V22D.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0



   2:REQUEST MESSAGE               :GEP-05, CLOSE N DV22A 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22A.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE N DV22A 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22A.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0




   2:REQUEST MESSAGE               :GEP-05, CLOSE R DV22A 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_CLOSE_V22A.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE R DV22A 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_CLOSE_V22A.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0


   2:REQUEST MESSAGE               :GEP-05, CLOSE N DV22B 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22B.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE N DV22B 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22B.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE R DV22B 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_CLOSE_V22B.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE R DV22B 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_CLOSE_V22B.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE N DV22C 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22C.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE N DV22C 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22C.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE R DV22C 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_CLOSE_V22C.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE R DV22C 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_CLOSE_V22C.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0



   2:REQUEST MESSAGE               :GEP-05, CLOSE N DV22D 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22D.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE N DV22D 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_255MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_75MS_NOM.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22D.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0


   2:REQUEST MESSAGE               :GEP-05, CLOSE R DV22D 75ms_I, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_CLOSE_V22D.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0

   2:REQUEST MESSAGE               :GEP-05, CLOSE R DV22D 75ms_II, NONE

  56:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_255MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  57:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_75MS_RED.CMM, 0
  57:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
  45:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 

   6:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_RED_ARM_CLOSE_V22D.CMM, 0
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  42:REQUEST MESSAGE               :GEP-05, Ready to measure!! , NONE 
  43:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_RED.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  44:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0 