   1:SEND COMMAND                  :CAN-02, C9F, CSP_ENA_DIS_DETECTION_1N_MD_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C9F, CSP_ENA_DIS_DETECTION_2N_MD_ENA.CMM, 0
   3:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:SEND COMMAND                  :CAN-02, C9F, CSP_ENA_DIS_DETECTION_1R_MD_ENA.CMM, 0
   6:SEND COMMAND                  :CAN-02, C9F, CSP_ENA_DIS_DETECTION_2R_MD_ENA.CMM, 0
   7:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE