  15:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  16:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_NOM_ARM_OPEN_V21A.CMM, 0
  17:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  18:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  19:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_NOM.CMM, 0
  20:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_NOM.CMM, 0
  21:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  15:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  16:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_RED_ARM_OPEN_V21B.CMM, 0
  17:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  18:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  19:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_RED.CMM, 0
  20:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_RED.CMM, 0
  21:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  15:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  16:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_NOM_ARM_OPEN_V21C.CMM, 0
  17:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  18:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  19:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_NOM.CMM, 0
  20:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_NOM.CMM, 0
  21:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  15:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  16:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_RED_ARM_OPEN_V21D.CMM, 0
  17:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  18:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  19:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_RED.CMM, 0
  20:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_RED.CMM, 0
  21:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
 
   2:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
