   1:REQUEST MESSAGE               :GEP-05, Hacer corto en CD TMP HTR_Vcab, NONE
   2:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   4:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_ON_CD.CMM, 0
   5:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   7:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
   8:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

   9:REQUEST MESSAGE               :GEP-05, Quitar corto y medir V_Debe ser 0, NONE
  10:REQUEST MESSAGE               :GEP-05, Se vuelve a poner a ON sin resetear, NONE
  11:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  12:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  13:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_ON_CD.CMM, 0
  14:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  15:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  16:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  17:REQUEST MESSAGE               :GEP-05, V Debe seguir siendo 0, NONE

  18:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  19:REQUEST MESSAGE               :GEP-05, Reset del LCL, NONE

  20:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_OFF_CD.CMM, 0
  21:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  22:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  23:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  24:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  25:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  26:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_ON_CD.CMM, 0
  27:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  28:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  29:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  30:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  31:REQUEST MESSAGE               :GEP-05, Medir V_Debe haber voltios, NONE

  32:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_OFF_CD.CMM, 0
  33:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  34:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  35:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  36:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  37:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  38:REQUEST MESSAGE               :GEP-05, Hacer corto en CL TMP HTR_Vcab, NONE
  39:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  40:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  41:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_ON_CL.CMM, 0
  42:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  43:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  44:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  45:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  46:REQUEST MESSAGE               :GEP-05, Quitar corto y medir V_Debe ser 0, NONE

  47:REQUEST MESSAGE               :GEP-05, Se vuelve a poner a ON sin resetear, NONE
  48:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  49:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  50:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_ON_CL.CMM, 0
  51:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  52:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  53:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0

  54:REQUEST MESSAGE               :GEP-05, V Debe seguir siendo 0, NONE
  55:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0

  56:REQUEST MESSAGE               :GEP-05, Reset del LCL, NONE
  57:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_OFF_CL.CMM, 0
  58:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  59:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  60:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  61:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  62:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  63:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_ON_CL.CMM, 0
  64:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  65:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  66:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  67:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  68:REQUEST MESSAGE               :GEP-05, Medir V_Debe haber voltios, NONE

  69:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_OFF_CL.CMM, 0
  70:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  71:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  72:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  73:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  74:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE