   1:SEND COMMAND                  :CAN-02, C95, CSP_AQS_CONFIGURATION_1R_DUR_MIN.CMM, 0
   2:SEND COMMAND                  :CAN-02, C95, CSP_AQS_CONFIGURATION_2R_DUR_MIN.CMM, 0
   3:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_TRDS11_75MS_RED.CMM, 0
   4:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_TRDS11_75MS_RED.CMM, 0
   5:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1R.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   7:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2R.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   9:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_RED_ARM_ON_CL.CMM, 0
  10:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  11:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  12:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_RED.CMM, 0
  13:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  14:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  15:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  16:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_RED_ARM_ON_PS.CMM, 0
  17:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  18:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  19:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_RED.CMM, 0
  20:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  21:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  22:SEND COMMAND                  :CAN-02, C7E, PS_INTERPOINT_DRIVER_ON_OFF_RED_ON.CMM, 0
  23:REQUEST MESSAGE               :GEP-05, POWER-ON 120V PS, NONE
  24:SEND COMMAND                  :CAN-02, C53, CCS_COMMANDING_ARM_DISARM_ARM.CMM, 0
  25:SEND COMMAND                  :CAN-02, C4E, CCS_ON_OFF_CONVERTERS_ALL_ON.CMM, 0
  26:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  27:SEND COMMAND                  :CAN-02, C4B, CCS_OPEN_CLOSE_SEMIC_SW_CLOSE.CMM, 0
  28:SEND COMMAND                  :CAN-02, C4D, CCS_ENA_DIS_OUTPUT_ENABLE.CMM, 0
  29:SEND COMMAND                  :CAN-02, C53, CCS_COMMANDING_ARM_DISARM_DISARM.CMM, 0
  30:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  31:REQUEST MESSAGE               :GEP-05, POWER-ON 120V PS, NONE
  32:SEND COMMAND                  :CAN-02, C1E, CAB_READ_AND_RESET_ERROR_INFO.CMM, 0
  33:REQUEST MESSAGE               :GEP-05, Verify that value of current is zero, NONE
  34:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_RED_ARM_OPEN_V21A.CMM, 0
  35:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  36:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  37:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_RED.CMM, 0
  38:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_RED.CMM, 0
  39:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  40:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  41:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  42:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_RED_ARM_OPEN_V21C.CMM, 0
  43:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  44:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  45:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_RED.CMM, 0
  46:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_RED.CMM, 0
  47:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  48:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  49:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  50:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_RED_ARM_OPEN_V56A.CMM, 0
  51:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  52:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  53:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_RED.CMM, 0
  54:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_RED.CMM, 0
  55:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  56:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  57:REQUEST MESSAGE               :GEP-05, This is a request message example, NON
  58:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_RED_ARM_CLOSE_V064.CMM, 0
  59:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  60:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  61:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_RED.CMM, 0
  62:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_RED.CMM, 0
  63:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  64:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  65:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  66:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_RED.CMM, 0
  67:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  68:REQUEST MESSAGE               :GEP-05, MEDIRRRRRRRR!!!!  !!!!, NONE
  69:SEND COMMAND                  :CAN-02, CBB, CSP_ARM_QUENCH_SEQ_RED.CMM, 0
  70:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  71:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_RED.CMM, 0
  72:SEND COMMAND                  :CAN-02, CBD, CSP_FIRE_QUENCH_RED.CMM, 0
  73:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  74:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  75:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  76:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_RED.CMM, 0
  77:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  78:SEND COMMAND                  :CAN-02, CBE, CSP_RESET_ALARM_AQS.CMM, 0
  79:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
  80:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  81:SEND COMMAND                  :CAN-02, C44, CCS_READ_SETPOINT_CMDS.cmm, 0
  82:SEND COMMAND                  :CAN-02, C53, CCS_COMMANDING_ARM_DISARM_ARM.CMM, 0
  83:SEND COMMAND                  :CAN-02, C4B, CCS_OPEN_CLOSE_SEMIC_SW_OPEN.CMM, 0
  84:SEND COMMAND                  :CAN-02, C4D, CCS_ENA_DIS_OUTPUT_DISABLE.CMM, 0
  85:SEND COMMAND                  :CAN-02, C4E, CCS_ON_OFF_CONVERTERS_ALL_OFF.CMM, 0
  86:SEND COMMAND                  :CAN-02, C53, CCS_COMMANDING_ARM_DISARM_DISARM.CMM, 0
  87:REQUEST MESSAGE               :GEP-05, POWER-OFF 120V PS, NONE
  88:SEND COMMAND                  :CAN-02, C7E, PS_INTERPOINT_DRIVER_ON_OFF_RED_OFF.CMM, 0
  89:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  90:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  91:SEND COMMAND                  :CAN-02, C1E, CAB_READ_AND_RESET_ERROR_INFO.CMM, 0
  92:INFO MESSAGE                  :GEP-06, ## Verify that value of current is zero