   1:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, C7D, PS_ON_OFF_CV_RED_OFF.CMM, 0
   4:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   6:SEND COMMAND                  :CAN-02, C7D, PS_ON_OFF_CV_RED_ON.CMM, 0
   7:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE