   1:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPA.CMM, 0
   4:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, MediRRRR!!!! Regeton , NONE
   6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20A_CLOSE_100MS.CMM, 0
   7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE