   1:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   3:SEND COMMAND                  :CAN-02, C71, PS_ENA_DIS_HT_HEATER_GROUP_NOM_ENA.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   5:SEND COMMAND                  :CAN-02, C72, PS_ENA_DIS_VACUUM_SENSOR_NOM_ENA.CMM, 0
   6:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   7:REQUEST MESSAGE               :GEP-05, This is a request message, NONE