   1:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_NOM.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:REQUEST MESSAGE               :GEP-05, MEDIRRRRRRRR!!!!  !!!!, NONE
   6:SEND COMMAND                  :CAN-02, CBB, CSP_ARM_QUENCH_SEQ_NOM.CMM, 0
   7:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   8:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_NOM.CMM, 0
   9:SEND COMMAND                  :CAN-02, CBD, CSP_FIRE_QUENCH_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  11:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  12:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  13:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_NOM.CMM, 0
  14:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  15:SEND COMMAND                  :CAN-02, CBE, CSP_RESET_ALARM_AQS.CMM, 0
  16:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  17:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE