   1:SEND COMMAND                  :CAN-02, C21, STM_ACQUIRE_NOM_ENER_DIS.CMM, 0
   2:SEND COMMAND                  :CAN-02, C22, STM_READ_NOM.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   4:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   6:SEND COMMAND                  :CAN-02, C47, CCS_ANALOG_TM_ACQUIRE.CMM, 0
   7:SEND COMMAND                  :CAN-02, C48, CCS_READ_ANALOG_TM.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE