   1:SEND COMMAND                  :CAN-02, C9C, CSP_WD_GET_COUNT_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, C9C, CSP_WD_GET_REMAINING_COUNT_NOM.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_ON_CD.CMM, 0
   6:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   7:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   8:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
   9:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  11:SEND COMMAND                  :CAN-02, C7E, PS_INTERPOINT_DRIVER_ON_OFF_NOM_ON.CMM, 0
  12:REQUEST MESSAGE               :GEP-05, POWER-ON 120V PS, NONE
  13:SEND COMMAND                  :CAN-02, C53, CCS_COMMANDING_ARM_DISARM_ARM.CMM, 0
  14:SEND COMMAND                  :CAN-02, C4E, CCS_ON_OFF_CONVERTERS_ALL_ON.CMM, 0
  15:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  16:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  17:SEND COMMAND                  :CAN-02, C4B, CCS_OPEN_CLOSE_SEMIC_SW_CLOSE.CMM, 0
  18:SEND COMMAND                  :CAN-02, C4D, CCS_ENA_DIS_OUTPUT_ENABLE.CMM, 0
  19:SEND COMMAND                  :CAN-02, C53, CCS_COMMANDING_ARM_DISARM_DISARM.CMM, 0
  20:SEND COMMAND                  :CAN-02, C1E, CAB_READ_AND_RESET_ERROR_INFO.CMM, 0
  21:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  22:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  23:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22A.CMM, 0
  24:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  25:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  26:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  27:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  28:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  29:SEND COMMAND                  :CAN-02, CED, CSP_ARM_DISARM_MOOG_VALVE_NOM_ARM_CLOSE_V22C.CMM, 0
  30:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  31:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  32:SEND COMMAND                  :CAN-02, CEE, CSP_OPERATE_MOOG_VALVE_NOM.CMM, 0
  33:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  34:REQUEST MESSAGE               :GEP-05, This is a request message , NONE 
  35:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_OFF_CL.CMM, 0
  36:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  37:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  38:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  39:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  40:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  41:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_NOM_ARM_CLOSE_V56A.CMM, 0
  42:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  43:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  44:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_NOM.CMM, 0
  45:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_NOM.CMM, 0
  46:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  47:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  48:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  49:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_NOM_ARM_CLOSE_V21A.CMM, 0
  50:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  51:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  52:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_NOM.CMM, 0
  53:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_NOM.CMM, 0
  54:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  55:SEND COMMAND                  :CAN-02, CE4, CSP_ARM_DISARM_BIL_VALVE_NOM_ARM_CLOSE_V21C.CMM, 0
  56:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  57:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  58:SEND COMMAND                  :CAN-02, CE7, CSP_OPERATE_BIL_VALVE_NOM.CMM, 0
  59:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_NOM.CMM, 0
  60:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  61:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  62:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 
  63:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_OFF_PS.CMM, 0
  64:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  65:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  66:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
  67:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  68:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  69:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_STEPS_DUR_MAX.CMM, 0
  70:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
  71:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  72:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_STEPS_DUR_MAX.CMM, 0
  73:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
  74:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  75:SEND COMMAND                  :CAN-02, C9C, CSP_WD_GET_COUNT_NOM.CMM, 0
  76:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  77:SEND COMMAND                  :CAN-02, C9C, CSP_WD_GET_REMAINING_COUNT_NOM.CMM, 0
  78:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  79:SEND COMMAND                  :CAN-02, CB1, CSP_ARM_DISARM_AUTO_RDS_NOM_ARM.CMM, 0
  80:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  81:SEND COMMAND                  :CAN-02, CB2, CSP_INITIATE_AUTO_RDS_NOM.CMM, 0
  82:SEND COMMAND                  :CAN-02, CB1, CSP_ARM_DISARM_AUTO_RDS_NOM_DIS.CMM, 0
  83:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  84:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  85:WAIT N SECONDS/MILLI-SECONDS  :GEP-04, 200, mSEC 
  86:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  87:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  88:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_NOM.CMM, 0
  89:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  90:WAIT N SECONDS/MILLI-SECONDS  :GEP-04, 60, SEC 
  91:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  92:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  93:WAIT N SECONDS/MILLI-SECONDS  :GEP-04, 70, SEC 
  94:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_NOM.CMM, 0
  95:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  96:WAIT N SECONDS/MILLI-SECONDS  :GEP-04, 1, SEC 
  97:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_NOM.CMM, 0
  98:REQUEST MESSAGE               :GEP-05, This is a request message example, NON
  99:WAIT N SECONDS/MILLI-SECONDS  :GEP-04, 60, SEC 
 100:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
 101:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
 102:WAIT N SECONDS/MILLI-SECONDS  :GEP-04, 60, SEC 
 103:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
 104:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
 105:WAIT N SECONDS/MILLI-SECONDS  :GEP-04, 60, SEC 
 106:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
 107:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
 108:WAIT N SECONDS/MILLI-SECONDS  :GEP-04, 18000, SEC 
   1:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, CBE, CSP_RESET_ALARM_RDS.CMM, 0
   4:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_NOM.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 