   1:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   3:SEND COMMAND                  :CAN-02, C71, PS_ENA_DIS_HT_HEATER_GROUP_NOM_DIS.CMM, 0
   1:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   5:SEND COMMAND                  :CAN-02, C72, PS_ENA_DIS_VACUUM_SENSOR_NOM_ENA.CMM, 0
   6:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   7:REQUEST MESSAGE               :GEP-05, Medir Vp en CH113, NONE
   1:READ POWER SIGNAL             :DMM-01, CAB, CCS_TO_ACTIVE_L_V, IF2, NONE, VOLTS
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   3:SEND COMMAND                  :CAN-02, C71, PS_ENA_DIS_HT_HEATER_GROUP_NOM_ENA.CMM, 0
   1:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   7:REQUEST MESSAGE               :GEP-05, Medir Vp en CH113, NONE
   1:READ POWER SIGNAL             :DMM-01, CAB, CCS_TO_ACTIVE_L_V, IF2, NONE, VOLTS
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   3:SEND COMMAND                  :CAN-02, C71, PS_ENA_DIS_HT_HEATER_GROUP_NOM_DIS.CMM, 0
   1:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   7:REQUEST MESSAGE               :GEP-05, Medir Vp en CH113, NONE
   1:READ POWER SIGNAL             :DMM-01, CAB, CCS_TO_ACTIVE_L_V, IF2, NONE, VOLTS
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   3:SEND COMMAND                  :CAN-02, C71, PS_ENA_DIS_HT_HEATER_GROUP_NOM_ENA.CMM, 0
   1:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   7:REQUEST MESSAGE               :GEP-05, Medir Vp en CH113, NONE
   1:READ POWER SIGNAL             :DMM-01, CAB, CCS_TO_ACTIVE_L_V, IF2, NONE, VOLTS
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   5:SEND COMMAND                  :CAN-02, C72, PS_ENA_DIS_VACUUM_SENSOR_NOM_DIS.CMM, 0
   6:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   7:REQUEST MESSAGE               :GEP-05, Medir Vp en CH113, NONE
   1:READ POWER SIGNAL             :DMM-01, CAB, CCS_TO_ACTIVE_L_V, IF2, NONE, VOLTS
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   5:SEND COMMAND                  :CAN-02, C72, PS_ENA_DIS_VACUUM_SENSOR_NOM_ENA.CMM, 0
   6:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   7:REQUEST MESSAGE               :GEP-05, Medir Vp en CH113, NONE
   1:READ POWER SIGNAL             :DMM-01, CAB, CCS_TO_ACTIVE_L_V, IF2, NONE, VOLTS
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   3:SEND COMMAND                  :CAN-02, C71, PS_ENA_DIS_HT_HEATER_GROUP_NOM_DIS.CMM, 0
   5:SEND COMMAND                  :CAN-02, C72, PS_ENA_DIS_VACUUM_SENSOR_NOM_DIS.CMM, 0
   6:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   7:REQUEST MESSAGE               :GEP-05, Medir Vp en CH113, NONE
   1:READ POWER SIGNAL             :DMM-01, CAB, CCS_TO_ACTIVE_L_V, IF2, NONE, VOLTS
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE