/********************************************************************
* ../source/rootElibdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../source/rootElibdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablerootElibdict();
extern void G__cpp_setup_inheritancerootElibdict();
extern void G__cpp_setup_typetablerootElibdict();
extern void G__cpp_setup_memvarrootElibdict();
extern void G__cpp_setup_globalrootElibdict();
extern void G__cpp_setup_memfuncrootElibdict();
extern void G__cpp_setup_funcrootElibdict();
extern void G__set_cpp_environmentrootElibdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../include/DHF.hh"
#include "../include/Cluster.hh"
#include "../include/Event.hh"
#include "../include/Align.hh"
#include "../include/Trace.hh"
#include "../include/Calib.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootElibdictLN_TClass;
extern G__linked_taginfo G__rootElibdictLN_TBuffer;
extern G__linked_taginfo G__rootElibdictLN_TDirectory;
extern G__linked_taginfo G__rootElibdictLN_TMemberInspector;
extern G__linked_taginfo G__rootElibdictLN_TObject;
extern G__linked_taginfo G__rootElibdictLN_TNamed;
extern G__linked_taginfo G__rootElibdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootElibdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootElibdictLN_TObjArray;
extern G__linked_taginfo G__rootElibdictLN_TClonesArray;
extern G__linked_taginfo G__rootElibdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__rootElibdictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__rootElibdictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TH1D;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TFile;
extern G__linked_taginfo G__rootElibdictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__rootElibdictLN_TLinearFitter;
extern G__linked_taginfo G__rootElibdictLN_Trace;
extern G__linked_taginfo G__rootElibdictLN_Align;
extern G__linked_taginfo G__rootElibdictLN_Cluster;
extern G__linked_taginfo G__rootElibdictLN_RHClass;
extern G__linked_taginfo G__rootElibdictLN_Event;
extern G__linked_taginfo G__rootElibdictLN_calib;
extern G__linked_taginfo G__rootElibdictLN_Calib;
extern G__linked_taginfo G__rootElibdictLN_DHF;

/* STUB derived class for protected member access */
