//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Oct 15 13:48:19 2002 by ROOT version 3.03/06)
//      from the StreamerInfo in file prv3.root
//////////////////////////////////////////////////////////


#ifndef MCEventGRoot02_h
#define MCEventGRoot02_h

#include "TObject.h"

class MCEventGRoot02 : public TObject {

public:
   int         Nskip;        //
   int         Particle;     //
   float       Coo[3];       //
   float       Dir[3];       //
   float       Momentum;     //
   float       Mass;         //
   float       Charge;       //

   MCEventGRoot02();
   virtual ~MCEventGRoot02();

   ClassDef(MCEventGRoot02,1) //
};

#endif
