//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Oct 15 13:48:19 2002 by ROOT version 3.03/06)
//      from the StreamerInfo in file prv3.root
//////////////////////////////////////////////////////////


#ifndef TRDClusterRoot_h
#define TRDClusterRoot_h

#include "TObject.h"
#include "TRef.h"

class TRDClusterRoot : public TObject {

public:
   int         Status;       //
   float       Coo[3];       //
   int         Layer;        //
   float       CooDir[3];    //
   int         Multip;       //
   int         HMultip;      //
   float       EDep;         //
   TRef        fTRDRawHit;   //

   TRDClusterRoot();
   virtual ~TRDClusterRoot();

   ClassDef(TRDClusterRoot,1) //
};

#endif
