#!/bin/csh
  chmod +x setinc
  setinc
  make x
  rm -f *.o
#...delete next 5 statements if you want to keep the source code:
  rm -f *.f
  rm -f  scatter7
  rm -f  partblk7
  rm -f  storbig 
  rm -f  sigmasx 
#...next statement leads to generation of events (as specified in file5):
  rqmd2_4  &

