   1:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPC.CMM, 0
   2:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   4:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20C_OPEN_45H.CMM, 0
   5:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   7:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_DIS_GROUPC.CMM, 0
   8:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
   9:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   10:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   11:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE