[ -z "$AMSWD" ] && AMSWD=".."
[ -z "$UNAME" ]      && UNAME=`(uname) 2>/dev/null`
[ -z "$UNAME" -a -d /sys/node_data ] && UNAME="DomainOS"
[ -z "$UNAME" ]      && (echo could not determine hosttype ; exit)

if [ "$UNAME" = "AIX" ] ; then
   MACHINE="aix"
elif [ "$UNAME" = "OSF1" ] ; then
    MACHINE="DEC-cxx"
elif [ "$UNAME" = "Linux" ] ; then
    MACHINE="$G4SYSTEM"
else
echo $UNAME is not supported yet

fi


$AMSWD/exe/$MACHINE/gbatch.exe <<!
LIST
KINE 14
LOSS 1
HADR 1
MULS 1
CKOV 1
RAYL 1
CUTS 1=0.0005 2=0.0005 3=0.001 4=0.001 5=0.001
TRIG 10000
DEBUG -1 10 1
C          Nparticles 
MISC 4=1 5=0      
MCGEN 1=-20. 2=-20. 3=190. 4=20. 5=20. 6=190. 12=-0.95 
13=10. 14=10. 15=0 16=1. 19=101 20=5 21=0
  
IOPA 1=3 2='g4g3v1.hbk' 43=2  
45='TriggerLVL1' 126=10000 
C RNDM 191483493 13582325
C      Simul Debug    CpuLim  Read Write Jobname
AMSJOB 1=0   2=0      3=50.   4=0  5=0  
C Special HP-UX
TIME 3=10000000
TERM 1234567890
L3REC 11=0
C G4FF 4=0
C TRDMC 1=-2
END
!
