#!/bin/sh

if (( $# >= 1))
then
    events2take=$1
else
    events2take=0
fi

echo "Now a scansion in TTH time will be performed taking $events2take for acquisition..."
echo "The list of TTH times to be scanned is in the file ./tthlist" 
sleep 3

for tthtime in `cat tthlist`; do

sleep 1
echo ""
echo ./runtth $tthtime $events2take
./runtth $tthtime $events2take
echo ""

done
