//
// File generated by rootcint at Thu Sep 11 17:18:06 2008

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mydict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void VCon_gb_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void VCon_gb_Dictionary();
   static void *new_VCon_gb(void *p = 0);
   static void *newArray_VCon_gb(Long_t size, void *p);
   static void delete_VCon_gb(void *p);
   static void deleteArray_VCon_gb(void *p);
   static void destruct_VCon_gb(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::VCon_gb*)
   {
      ::VCon_gb *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::VCon_gb),0);
      static ::ROOT::TGenericClassInfo 
         instance("VCon_gb", "VCon_gbatch.h", 6,
                  typeid(::VCon_gb), DefineBehavior(ptr, ptr),
                  0, &VCon_gb_Dictionary, isa_proxy, 0,
                  sizeof(::VCon_gb) );
      instance.SetNew(&new_VCon_gb);
      instance.SetNewArray(&newArray_VCon_gb);
      instance.SetDelete(&delete_VCon_gb);
      instance.SetDeleteArray(&deleteArray_VCon_gb);
      instance.SetDestructor(&destruct_VCon_gb);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::VCon_gb*)
   {
      return GenerateInitInstanceLocal((::VCon_gb*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::VCon_gb*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void VCon_gb_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::VCon_gb*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_VCon_gb(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::VCon_gb : new ::VCon_gb;
   }
   static void *newArray_VCon_gb(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::VCon_gb[nElements] : new ::VCon_gb[nElements];
   }
   // Wrapper around operator delete
   static void delete_VCon_gb(void *p) {
      delete ((::VCon_gb*)p);
   }
   static void deleteArray_VCon_gb(void *p) {
      delete [] ((::VCon_gb*)p);
   }
   static void destruct_VCon_gb(void *p) {
      typedef ::VCon_gb current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::VCon_gb

/********************************************************
* mydict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablemydict();

extern "C" void G__set_cpp_environmentmydict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("VCon_gbatch.h");
  G__cpp_reset_tagtablemydict();
}
#include <new>
extern "C" int G__cpp_dllrevmydict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* VCon_gb */
static int G__mydict_113_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   VCon_gb* p = NULL;
   long gvp = G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new VCon_gb((AMSContainer*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) VCon_gb((AMSContainer*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new VCon_gb[n];
       } else {
         p = new((void*) gvp) VCon_gb[n];
       }
     } else {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new VCon_gb;
       } else {
         p = new((void*) gvp) VCon_gb;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__mydictLN_VCon_gb);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mydict_113_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   VCon_gb* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new VCon_gb(*(VCon_gb*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__mydictLN_VCon_gb);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef VCon_gb G__TVCon_gb;
static int G__mydict_113_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (VCon_gb*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((VCon_gb*) (soff+(sizeof(VCon_gb)*i)))->~G__TVCon_gb();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (VCon_gb*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((VCon_gb*) (soff))->~G__TVCon_gb();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mydict_113_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   VCon_gb* dest = (VCon_gb*) G__getstructoffset();
   *dest = *(VCon_gb*) libp->para[0].ref;
   const VCon_gb& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* VCon_gb */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmydict {
 public:
  G__Sizep2memfuncmydict(): p(&G__Sizep2memfuncmydict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmydict::*p)();
};

size_t G__get_sizep2memfuncmydict()
{
  G__Sizep2memfuncmydict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemydict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mydictLN_VCon_gb))) {
     VCon_gb *G__Lderived;
     G__Lderived=(VCon_gb*)0x1000;
     {
       VCon *G__Lpbase=(VCon*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mydictLN_VCon_gb),G__get_linked_tagnum(&G__mydictLN_VCon),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemydict() {

   /* Setting up typedef entry */
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* VCon_gb */
static void G__setup_memvarVCon_gb(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mydictLN_VCon_gb));
   { VCon_gb *p; p=(VCon_gb*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->con)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__mydictLN_AMSContainer),-1,-1,1,"con=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmydict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncVCon_gb(void) {
   /* VCon_gb */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mydictLN_VCon_gb));
   G__memfunc_setup("VCon_gb",670,G__mydict_113_0_1, 105, G__get_linked_tagnum(&G__mydictLN_VCon_gb), -1, 0, 1, 1, 1, 0, "U 'AMSContainer' - 0 '0' cc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCont",692,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__mydictLN_VCon), -1, 0, 1, 1, 1, 0, "C - - 0 - name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("getnelem",849,(G__InterfaceMethod) NULL,105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("eraseC",595,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("getelem",739,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__mydictLN_AMSlink), -1, 0, 1, 1, 1, 0, "i - - 0 - ii", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("addnext",744,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'AMSlink' - 0 - aa", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("VCon_gb", 670, G__mydict_113_0_7, (int) ('i'), G__get_linked_tagnum(&G__mydictLN_VCon_gb), -1, 0, 1, 1, 1, 0, "u 'VCon_gb' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~VCon_gb", 796, G__mydict_113_0_8, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mydict_113_0_9, (int) ('u'), G__get_linked_tagnum(&G__mydictLN_VCon_gb), -1, 1, 1, 1, 1, 0, "u 'VCon_gb' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmydict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmydict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmydict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mydictLN_AMSlink = { "AMSlink" , 99 , -1 };
G__linked_taginfo G__mydictLN_AMSContainer = { "AMSContainer" , 99 , -1 };
G__linked_taginfo G__mydictLN_VCon = { "VCon" , 99 , -1 };
G__linked_taginfo G__mydictLN_VCon_gb = { "VCon_gb" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemydict() {
  G__mydictLN_AMSlink.tagnum = -1 ;
  G__mydictLN_AMSContainer.tagnum = -1 ;
  G__mydictLN_VCon.tagnum = -1 ;
  G__mydictLN_VCon_gb.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemydict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mydictLN_AMSlink);
   G__get_linked_tagnum_fwd(&G__mydictLN_AMSContainer);
   G__get_linked_tagnum_fwd(&G__mydictLN_VCon);
   G__tagtable_setup(G__get_linked_tagnum(&G__mydictLN_VCon_gb),sizeof(VCon_gb),-1,1280,(char*)NULL,G__setup_memvarVCon_gb,G__setup_memfuncVCon_gb);
}
extern "C" void G__cpp_setupmydict(void) {
  G__check_setup_version(30051515,"G__cpp_setupmydict()");
  G__set_cpp_environmentmydict();
  G__cpp_setup_tagtablemydict();

  G__cpp_setup_inheritancemydict();

  G__cpp_setup_typetablemydict();

  G__cpp_setup_memvarmydict();

  G__cpp_setup_memfuncmydict();
  G__cpp_setup_globalmydict();
  G__cpp_setup_funcmydict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmydict();
  return;
}
class G__cpp_setup_initmydict {
  public:
    G__cpp_setup_initmydict() { G__add_setup_func("mydict",(G__incsetup)(&G__cpp_setupmydict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmydict() { G__remove_setup_func("mydict"); }
};
G__cpp_setup_initmydict G__cpp_setup_initializermydict;

