//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Oct 15 13:48:19 2002 by ROOT version 3.03/06)
//      from the StreamerInfo in file prv3.root
//////////////////////////////////////////////////////////


#ifndef TRDMCClusterRoot_h
#define TRDMCClusterRoot_h

#include "TObject.h"

class TRDMCClusterRoot : public TObject {

public:
   int         Layer;        //
   int         Ladder;       //
   int         Tube;         //
   int         TrackNo;      //
   float       Edep;         //
   float       Ekin;         //
   float       Xgl[3];       //
   float       Step;         //

   TRDMCClusterRoot();
   virtual ~TRDMCClusterRoot();

   ClassDef(TRDMCClusterRoot,1) //
};

#endif
