#!/bin/sh


cont=10
max=30
events=180000


while [ $cont -le $max ]; do

echo $cont
echo ln -s JINF_01_$cont.conf JINF_01.conf
ln -s JINF_01_$cont.conf JINF_01.conf

echo ./TakeJEPP  0 COMPLETERUN $events 0
./TakeJEPP  0 COMPLETERUN $events 0

echo rm -f JINF_01.conf
rm -f JINF_01.conf
sleep 10

cont=`expr $cont + 5`
echo $cont

done


cont=40
max=100
events=180000


while [ $cont -le $max ]; do

echo $cont
echo ln -s JINF_01_$cont.conf JINF_01.conf
ln -s JINF_01_$cont.conf JINF_01.conf

echo ./TakeJEPP  0 COMPLETERUN $events 0
./TakeJEPP  0 COMPLETERUN $events 0

echo rm -f JINF_01.conf
rm -f JINF_01.conf
sleep 10

cont=`expr $cont + 10`
echo $cont

done
