#!/bin/sh


cont=115
max=245
#events=50000


while [ $cont -le $max ]; do

echo ln -s JINF_01_$cont.conf JINF_01.conf
ln -s JINF_01_$cont.conf JINF_01.conf

echo ./TakeJEPP  0 CALIB 1 
./TakeJEPP  0 CALIB 1

echo rm -f JINF_01.conf
rm -f JINF_01.conf
sleep 10

cont=`expr $cont + 10`

done
