   3:SEND COMMAND                  :CAN-02, CC6, CSP_GET_DETECTOR_STATUS_RED.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   1:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_RED.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   2:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   4:SEND COMMAND                  :CAN-02, CC9, CSP_GET_VALVES_STATUS_RED.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE