   1:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_1N.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:SEND COMMAND                  :CAN-02, CCC, CSP_GET_RDS_AQS_CONFIGURATION_2N.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   7:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1N_TRDS11_75MS_NOM.CMM, 0
   8:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2N_TRDS11_75MS_NOM.CMM, 0
   9:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_1R_STEPS_DUR_NOM.CMM, 0
  10:SEND COMMAND                  :CAN-02, C93, CSP_RDS_CONFIGURATION_2R_STEPS_DUR_NOM.CMM, 0