   1:SEND COMMAND                  :CAN-02, CC6, CSP_GET_DETECTOR_STATUS_NOM.CMM, 0 
   2:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   3:SEND COMMAND                  :CAN-02, CC3, CSP_GET_ALARM_SUMMARY_NOM.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   5:SEND COMMAND                  :CAN-02, CBE, CSP_RESET_ALARM_AQS.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   7:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   9:SEND COMMAND                  :CAN-02, C1E, CAB_READ_AND_RESET_ERROR_INFO.CMM, 0
  10:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  11:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE