   2:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   2:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_RED_ARM_ON_PS.CMM, 0
   2:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_RED.CMM, 0
   4:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   1:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_RED_ARM_OFF_PS.CMM, 0
   2:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_RED.CMM, 0
   4:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE


