   1:SEND COMMAND                  :CAN-02, C9F, CSP_ENA_DIS_DETECTION_1R_MD_DIS.CMM, 0
   2:SEND COMMAND                  :CAN-02, C9F, CSP_ENA_DIS_DETECTION_2R_MD_DIS.CMM, 0
   3:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_RED.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:SEND COMMAND                  :CAN-02, CC6, CSP_GET_DETECTOR_STATUS_RED.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE