   5:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   1:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_ON_CD.CMM, 0
   2:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   4:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
   5:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   7:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   1:SEND COMMAND                  :CAN-02, CE1, CSP_ARM_DISARM_HEATER_NOM_ARM_OFF_CD.CMM, 0
   2:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   4:SEND COMMAND                  :CAN-02, CE2, CSP_OPERATE_HEATER_NOM.CMM, 0
   5:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   7:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE