   1:SEND COMMAND                  :CAN-02, C44, CCS_READ_SETPOINT_CMDS.cmm, 0
   2:SEND COMMAND                  :CAN-02, C53, CCS_COMMANDING_ARM_DISARM_ARM.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   4:SEND COMMAND                  :CAN-02, C4B, CCS_OPEN_CLOSE_SEMIC_SW_OPEN.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   6:SEND COMMAND                  :CAN-02, C4D, CCS_ENA_DIS_OUTPUT_DISABLE.CMM, 0
   7:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   8:SEND COMMAND                  :CAN-02, C4E, CCS_ON_OFF_CONVERTERS_ALL_OFF.CMM, 0
   9:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  10:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  11:SEND COMMAND                  :CAN-02, C53, CCS_COMMANDING_ARM_DISARM_DISARM.CMM, 0
  12:REQUEST MESSAGE               :GEP-05, POWER-OFF 120V PS, NONE
  13:SEND COMMAND                  :CAN-02, C7E, PS_INTERPOINT_DRIVER_ON_OFF_NOM_OFF.CMM, 0
  14:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  15:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
  16:SEND COMMAND                  :CAN-02, C1E, CAB_READ_AND_RESET_ERROR_INFO.CMM, 0
  17:INFO MESSAGE                  :GEP-06, ## Verify that value of current is zero