  2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE PS_MOOG VALVE DV20A, NONE

   6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPA.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20A_OPEN_255MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
 
  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPA.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20A_OPEN_2MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPA.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20A_OPEN_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE


  2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE PS_MOOG VALVE DV20B, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPB.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20B_OPEN_255MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
 
  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPB.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20B_OPEN_2MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPB.CMM, 0
  4:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20B_OPEN_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE PS_MOOG VALVE DV20C, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPC.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20C_OPEN_255MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPC.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20C_OPEN_2MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPC.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20C_OPEN_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  2:REQUEST MESSAGE               :GEP-05, Measure with SCOPE PS_MOOG VALVE DV20D, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPD.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20D_OPEN_255MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE 

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPD.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  9:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20D_OPEN_2MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE  
 11:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPD.CMM, 0
  4:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20D_OPEN_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
 
 10:REQUEST MESSAGE               :GEP-05, CHANGE DV20A TO CLOSE measure by Nominal electronics & configure the scope, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPA.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE  
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20A_CLOSE_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

 10:REQUEST MESSAGE               :GEP-05, measure DV20B TO CLOSE by Redundant electronics & configure the scope, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPA.CMM, 0
  4:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20A_CLOSE_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

 10:REQUEST MESSAGE               :GEP-05, measure DV20B TO CLOSE by Nominal electronics & configure the scope, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPB.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE  
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20B_CLOSE_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

 10:REQUEST MESSAGE               :GEP-05, CHANGE DV20B TO CLOSE measure by Redundant electronics & configure the scope, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPB.CMM, 0
  4:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20B_CLOSE_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

 10:REQUEST MESSAGE               :GEP-05, CHANGE DV20C TO CLOSE measure by Nominal electronics & configure the scope, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPC.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE  
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20C_CLOSE_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

 10:REQUEST MESSAGE               :GEP-05, measure DV20C TO CLOSE by Redundant electronics & configure the scope, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPC.CMM, 0
  4:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20C_CLOSE_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

 10:REQUEST MESSAGE               :GEP-05, measure DV20D TO CLOSE by Nominal electronics & configure the scope, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_NOM_ENA_GROUPD.CMM, 0
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE  
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_NOM_V20D_CLOSE_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_NOM.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE

 10:REQUEST MESSAGE               :GEP-05, CHANGE DV20D TO CLOSE measure by Redundant electronics & configure the scope, NONE

  6:SEND COMMAND                  :CAN-02, C79, PS_ENA_DIS_MOOG_VALVES_RED_ENA_GROUPD.CMM, 0
  4:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
  6:SEND COMMAND                  :CAN-02, C7C, PS_OPERATE_MOOG_VALVE_RED_V20D_CLOSE_100MS.CMM, 0
 10:REQUEST MESSAGE               :GEP-05, check the amplitude & width on the scope, NONE
  7:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
  6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE