   1:SEND COMMAND                  :CAN-02, CCA, CSP_ARM_DISARM_CANCEL_AUTO_RDS_NOM_ARM.CMM, 0
   2:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   3:SEND COMMAND                  :CAN-02, CB4, CSP_INITIATE_CANCEL_AUTO_RDS_NOM.CMM, 0
   4:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:SEND COMMAND                  :CAN-02, CCA, CSP_ARM_DISARM_CANCEL_AUTO_RDS_NOM_DIS.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   7:SEND COMMAND                  :CAN-02, CB4, CSP_INITIATE_CANCEL_AUTO_RDS_NOM.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   9:SEND COMMAND                  :CAN-02, CC5, CSP_GET_GENERAL_STATUS_NOM.CMM, 0
  10:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE