   1:CONFIGURE CHANNEL             :LDS-02, RBL_488, RESISTENCE, 17.000, 500000.000, 500000.000
   2:ENABLE/DISABLE INPUT          :LDS-04, RBL_488, ENABLE
   3:ACQUIRE MEASUREMENT           :LDS-05, RBL_488, RESISTENCE
   4:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   5:RAMP-UP LOOP                  :RAU-01, 10, 10, 0, TEST_2.TXT
   6:ACQUIRE MEASUREMENT           :LDS-05, RBL_488, RESISTENCE
   7:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE