   1:SEND COMMAND                  :CAN-02, C24, STM_ACQUIRE_COLD_VALVE_STATUS_RED.CMM, 0
   2:SEND COMMAND                  :CAN-02, C27, STM_READ_COLD_VALVE_STATUS_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   4:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE