   1:SEND COMMAND                  :CAN-02, C7E, PS_INTERPOINT_DRIVER_ON_OFF_RED_OFF.CMM, 0
   2:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message, NONE
   4:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   5:REQUEST MESSAGE               :GEP-05, This is a request message, NONE