#!/bin/sh


cont=0
max=1000
events=0


while [ $cont -le $max ]; do

#echo ./Calib 
#./Calib

echo ./TakeJinjJMDC 0 INIT
./TakeJinjJMDC 0 INIT


echo ./TakeJinjJMDC 0 COMPLETERUN $events 
./TakeJinjJMDC 0 COMPLETERUN $events

sleep 2

#cont=`expr $cont + 1`

done
