#!/bin/sh

if (( $# >= 1))
then
    tthtime=$1
else
    echo "No parameter for the dalay to be applied was passed, using the standard one!"
    tthtime=2500
fi

if (( $# >= 2))
then
    events2take=$2
else
    events2take=0
fi

echo "Now will be changed the TTH time to $tthtime nanoseconds and will be performed a sequence INIT-CALIB-RUN, taking $events2take events during run"

echo ""
echo "---------------------------------------------------------------------------------------------------"
echo "Calling the ./tth script: ./tth $tthtime..."
./tth $tthtime
echo "---------------------------------------------------------------------------------------------------"
echo ""
echo ./TakeJinjJMDC 0 INIT
./TakeJinjJMDC 0 INIT
data=`date`
echo "$data:      -> initialization with delay $tthtime"
echo "$data:      -> initialization with delay $tthtime" >> shortlog.txt
echo ./TakeJinjJMDC 0 COMPLETERUN $events2take
./TakeJinjJMDC 0 COMPLETERUN $events2take