//
// File generated by rootcint at Wed Sep 29 16:20:20 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "slowguiDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void SlowGui_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void SlowGui_Dictionary();
   static void delete_SlowGui(void *p);
   static void deleteArray_SlowGui(void *p);
   static void destruct_SlowGui(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::SlowGui*)
   {
      ::SlowGui *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::SlowGui),0);
      static ::ROOT::TGenericClassInfo 
         instance("SlowGui", "./slowgui.h", 73,
                  typeid(::SlowGui), DefineBehavior(ptr, ptr),
                  0, &SlowGui_Dictionary, isa_proxy, 0,
                  sizeof(::SlowGui) );
      instance.SetDelete(&delete_SlowGui);
      instance.SetDeleteArray(&deleteArray_SlowGui);
      instance.SetDestructor(&destruct_SlowGui);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::SlowGui*)
   {
      return GenerateInitInstanceLocal((::SlowGui*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SlowGui*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void SlowGui_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::SlowGui*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrapper around operator delete
   static void delete_SlowGui(void *p) {
      delete ((::SlowGui*)p);
   }
   static void deleteArray_SlowGui(void *p) {
      delete [] ((::SlowGui*)p);
   }
   static void destruct_SlowGui(void *p) {
      typedef ::SlowGui current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::SlowGui

/********************************************************
* slowguiDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableslowguiDict();

extern "C" void G__set_cpp_environmentslowguiDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("slowgui.h");
  G__cpp_reset_tagtableslowguiDict();
}
#include <new>
extern "C" int G__cpp_dllrevslowguiDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SlowGui */
static int G__slowguiDict_783_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SlowGui* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 6
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new SlowGui(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (unsigned int) G__int(libp->para[4]), (int) G__int(libp->para[5]));
   } else {
     p = new((void*) gvp) SlowGui(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (unsigned int) G__int(libp->para[4]), (int) G__int(libp->para[5]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__slowguiDictLN_SlowGui));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateTpsfe((AMSWcom*) G__int(libp->para[0]), (ushort) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateS9011ATFrame((TGCompositeFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateTBSFrame((TGCompositeFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateTpsfeFrame((TGCompositeFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CheckTab((Int_t) G__int(libp->para[0]), (Char_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->Exit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CheckSlowControl();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->FillTpsfePage((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((SlowGui*) G__getstructoffset())->TPSFEtoTDR((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ControlTpsfe((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->GetTpsfeStatus((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->GetTpsfeTrips((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchTpsfeTdr((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchTpsfeLrs((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchTpsfeLrk((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchTpsfeAll((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchTpsfeTdrAll((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchTpsfeLrsAll((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchTpsfeLrkAll((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchTpsfeAllAll((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CheckMainTab((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CheckTpsfeClickDockable((Event_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateSettingsFrame((TGCompositeFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SelectCommunicationMode((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SelectCommunicationPort((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ApplyAMSWire();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->FillTbsPage((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateTbs((AMSWcom*) G__int(libp->para[0]), (ushort) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->GetTbsStatus((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CheckTbsClickDockable((Event_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CheckTbsUndock();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CheckTbsDock();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ControlTbsVoltage((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->DisplayTbsStatus((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ShowBrotherTrip((SlowControl*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ShowPowerOn((SlowControl*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SelectActel((sACTEL) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Char_t*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchActel((sACTEL) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Char_t*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateS9011AT((AMSWcom*) G__int(libp->para[0]), (ushort) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateS9051Page((TGCompositeFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateS9053Page((TGCompositeFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateS9055Page((TGCompositeFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateTripIndicator((TGCompositeFrame*) G__int(libp->para[0]), (TGLabel**) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreatePowerOnIndicator((TGCompositeFrame*) G__int(libp->para[0]), (TGLabel**) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ShowTripIndicator((TGLabel*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ShowPowerOnIndicator((TGLabel*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateTextButton((TGCompositeFrame*) G__int(libp->para[0]), (TGTextButton**) G__int(libp->para[1])
, (const Char_t*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->DisplayHelp((Char_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SlowGui*) G__getstructoffset())->CreateHelpButton((TGCompositeFrame*) G__int(libp->para[0]), (const Char_t*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SlowGui*) G__getstructoffset())->CreateRefreshButton((TGCompositeFrame*) G__int(libp->para[0]), (const Char_t*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((SlowGui*) G__getstructoffset())->CreateInitLecroyButton((TGCompositeFrame*) G__int(libp->para[0]), (const Char_t*) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->GetTbsADCBiasVoltage((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ControlTbsLr((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((SlowGui*) G__getstructoffset())->UpdateTbsBiasVoltage((Int_t) G__int(libp->para[0]), (ushort) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((SlowGui*) G__getstructoffset())->UpdateTbsBiasVoltage((Int_t) G__int(libp->para[0]), (ushort) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->UpdateTbsBiasCurrent((Int_t) G__int(libp->para[0]), (ushort) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((SlowGui*) G__getstructoffset())->UpdateTbsBiasCurrents((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((SlowGui*) G__getstructoffset())->UpdateTbsBiasCurrents((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->GetTbsADCBiasCurrent((Int_t) G__int(libp->para[0]), (ushort) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->GetTbsADCBiasCurrents((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((SlowGui*) G__getstructoffset())->LightColor((Pixel_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((SlowGui*) G__getstructoffset())->ShowTpsfeTrips((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((SlowGui*) G__getstructoffset())->ShowTpsfeTrips((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((SlowGui*) G__getstructoffset())->ADCtoVolt((ushort) G__int(libp->para[0]), (ushort) G__int(libp->para[1])
, (ushort) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((SlowGui*) G__getstructoffset())->ADCtoCurrent((ushort) G__int(libp->para[0]), (ushort) G__int(libp->para[1])
, (ushort) G__int(libp->para[2]), (Int_t) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ShowTbsEmpty((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_71(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->DisplayTpsfeStatus((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->GetS9011atStatus();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->DisplayS9011atStatus();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ShowTpsfeEmpty((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ControlS9051((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_76(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ControlS9053((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_77(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ControlS9055((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_78(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SelectADCmode((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_79(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ShowS9011atEmpty();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_80(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateOvercurrentIndicator((TGCompositeFrame*) G__int(libp->para[0]), (TGLabel**) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_81(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ShowOvercurrentIndicator((TGLabel*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_82(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CalibrateADCCurrent((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_83(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ReadADCCurrentCalib((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_84(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreatePlotFrame((TGCompositeFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_85(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreatePlot();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_86(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((SlowGui*) G__getstructoffset())->NewCanvas((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (const Char_t*) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((SlowGui*) G__getstructoffset())->NewCanvas((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_87(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CreateTDRPlotPage((TGCompositeFrame*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_88(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->UpdateCanvases();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_89(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->RefreshCanvas((TCanvas*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_90(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->InitGraphs();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_91(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->FillGraphs();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_92(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->OpenDataFile((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_93(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->CloseDataFile();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_94(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SetButtonColor((TGTextButton*) G__int(libp->para[0]), (Pixel_t) G__int(libp->para[1])
, (Pixel_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_95(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SetS9011DCDCButton((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (TGTextButton*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_96(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SwitchAutoMode((Int_t) G__int(libp->para[0]), (Char_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_97(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->InitLecroy((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_98(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->TrackerMonitor();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_99(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->ProcessCanvas((TVirtualPad*) G__int(libp->para[0]), (TObject*) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_100(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->UpdateZoomCanvases();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_101(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->InitGraph((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_102(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->FillTKGraph((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_103(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->UpdateCurrent2((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_104(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->RefreshCanvas((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_105(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->UpdateTKTrips((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_106(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->DisplayTKVoltages((int) G__int(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_107(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->UpdateTKBiasVoltage((Int_t) G__int(libp->para[0]), (ushort) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_108(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->RefreshAll();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_109(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->InitCorrCurrent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_110(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->UpdateTKTPSFE((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_111(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->EnableS9053();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_112(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->TestAMSW((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__slowguiDict_783_0_113(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SlowGui*) G__getstructoffset())->SetTimerDelay((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__slowguiDict_783_0_114(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SlowGui* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SlowGui(*(SlowGui*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__slowguiDictLN_SlowGui));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SlowGui G__TSlowGui;
static int G__slowguiDict_783_0_115(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SlowGui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SlowGui*) (soff+(sizeof(SlowGui)*i)))->~G__TSlowGui();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SlowGui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SlowGui*) (soff))->~G__TSlowGui();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__slowguiDict_783_0_116(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SlowGui* dest = (SlowGui*) G__getstructoffset();
   *dest = *(SlowGui*) libp->para[0].ref;
   const SlowGui& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SlowGui */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncslowguiDict {
 public:
  G__Sizep2memfuncslowguiDict(): p(&G__Sizep2memfuncslowguiDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncslowguiDict::*p)();
};

size_t G__get_sizep2memfuncslowguiDict()
{
  G__Sizep2memfuncslowguiDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceslowguiDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableslowguiDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__slowguiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__slowguiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__slowguiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__slowguiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__slowguiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__slowguiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Pixel_t",107,-1,0,-1);
   G__setnewtype(-1,"Pixel value",0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__slowguiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__slowguiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__slowguiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__slowguiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__slowguiDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__slowguiDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__slowguiDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__slowguiDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__slowguiDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__slowguiDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__slowguiDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ushort",114,-1,0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SlowGui */
static void G__setup_memvarSlowGui(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__slowguiDictLN_SlowGui));
   { SlowGui *p; p=(SlowGui*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGMainFrame),-1,-1,4,"fMain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGMainFrame),-1,-1,4,"fTrackerMonitorMainFrame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGHorizontalFrame),-1,-1,4,"fFrame1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGHorizontalFrame),-1,-1,4,"fFrame2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTab),-1,-1,4,"fTab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTab),-1,-1,4,"fTBSTab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTab),-1,-1,4,"fTPSFETab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTab),-1,-1,4,"fPlotTab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL31=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL32=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL33=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL34=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL35=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL5=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL7=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL71=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL72=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL73=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL74=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL75=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL76=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL77=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL78=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLayoutHints),-1,-1,4,"fL79=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"tf=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"fF1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"fF2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"tS9011main=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"tTPSFEmain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"tTBSmain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"tSettingsTab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"tPlotTab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"tTPSFEpage[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCompositeFrame),-1,-1,4,"tTBSpage[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tTPSFETdrLabel[4][7]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"TripLabelSSF[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"TripLabelLRS[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"TripLabelLRK[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tS9051TripLabel[4][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tS9053TripLabel[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tS9055TripLabel[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tS9051OvercurrentLabel[4][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tS9053OvercurrentLabel[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tS9055OvercurrentLabel[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTPSFEActelHotButton[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTPSFEActelColdButton[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTBSActelHotButton[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTBSActelColdButton[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tS9011ATActelHotButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tS9011ATActelColdButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGComboBox),-1,-1,4,"tTPSFEActelCombo[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGComboBox),-1,-1,4,"tTBSActelCombo[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGComboBox),-1,-1,4,"tS9011ATActelCombo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTDRSSF[4][7]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTDRLRS[4][7]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTDRLRK[4][7]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTDRALL[4][7]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGDockableFrame),-1,-1,4,"TripFrame[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGDockableFrame),-1,-1,4,"ADCcurrentFrame[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTBSLRhot[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTBSLRcold[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTBSVOLT80[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTBSVOLT60[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tTBSGetVOLT[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tTBSADChot[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tTBSADCcold[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tButTBSADCcurrent[2][12]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tButTBSADCcurrentsALL[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tTBSADCcurrent[2][12]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tTBSTripIndicator[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tTBSPowerOnIndicator[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tTPSFETripIndicator[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tTPSFEPowerOnIndicator[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tS9011ATTripIndicator=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"tS9011ATPowerOnIndicator=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tS9051DCDC[4][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tS9053DCDC[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGTextButton),-1,-1,4,"tS9055DCDC[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCheckButton),-1,-1,4,"tAutoSSFButton[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCheckButton),-1,-1,4,"tAutoLRSButton[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCheckButton),-1,-1,4,"tAutoLRKButton[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCheckButton),-1,-1,4,"tS9053Enable=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGNumberEntry),-1,-1,4,"tAMSWaddr=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGNumberEntry),-1,-1,4,"tTimerDel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TTimer),-1,-1,4,"TimerCheck=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TCanvas),-1,-1,4,"PlotCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGraph),-1,-1,4,"LadderCurrent[24]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGCheckButton),-1,-1,4,"PlotTDR[24]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_AMSWcom),-1,-1,4,"Node=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TPSFE),-1,-1,4,"MyTpsfe[4][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TBS),-1,-1,4,"MyTbs[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_S9011AT),-1,-1,4,"MyS9011AT[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sACTEL),-1,-1,4,"ActelTpsfe[4]=",0,"active actel mode ");
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sACTEL),-1,-1,4,"ActelTbs[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sACTEL),-1,-1,4,"ActelS9011AT=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sActelMode),-1,-1,4,"ActelTbsState[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sActelMode),-1,-1,4,"ActelTpsfeState[4][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sActelMode),-1,-1,4,"ActelS9011ATState[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sVOLT),-1,-1,4,"Voltages[2][4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"TBSlrState[2][4]=",0,"k0A, k0B, k1A, k1B");
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"TDRSSFstate[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"TDRLRSstate[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"TDRLRKstate[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"S9051state[4][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"S9053state[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"S9055state[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"S9051overc[4][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"S9053overc[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"S9055overc[2][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"AutoSSF[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"AutoLRS[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__slowguiDictLN_sDCDC),-1,-1,4,"AutoLRK[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"CorrADC[2][12]=",0,(char*)NULL);
   G__memvar_setup((void*)0,107,0,0,-1,G__defined_typename("Pixel_t"),-1,4,"PixelColor[20][2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"TPSFETabColor[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"TBSTabColor[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"ADCmode=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"CanvasCount=",0,(char*)NULL);
   G__memvar_setup((void*)0,69,0,0,-1,-1,-1,4,"DataFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TFile),-1,-1,4,"RootFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TCanvas),-1,-1,4,"LadCan[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TCanvas),-1,-1,4,"LadCanZoom[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TTree),-1,-1,4,"LadGraph[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGHProgressBar),-1,-1,4,"fHProgressLeak[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGStatusBar),-1,-1,4,"fStatusPwg[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"fLabelTripS[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"fLabelTripScnt[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"fLabelTripK[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"fLabelTripKcnt[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"fLabelTripT[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"fLabelTripTcnt[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"fSlabel[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"fKlabel[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TGLabel),-1,-1,4,"fTlabel[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,107,0,0,-1,G__defined_typename("ULong_t"),-1,4,"PwgCol[4]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"ladmax=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"zoomcounter=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"zoommin=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__slowguiDictLN_TrackerLadders),-1,-1,4,"InnerTracker=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"Tim[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"Current[4][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"AMSWmode=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"AMSWport=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"TCrate=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarslowguiDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSlowGui(void) {
   /* SlowGui */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__slowguiDictLN_SlowGui));
   G__memfunc_setup("InitStyle",933,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTabColor",1090,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"U 'TGTab' - 0 - aTab C - 'Char_t' 0 - name "
"k - 'Pixel_t' 0 - color", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTabColor",1090,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"U 'TGTab' - 0 - aTab i - 'Int_t' 0 - index "
"k - 'Pixel_t' 0 - color", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTabColor",1401,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "C - 'Char_t' 10 - type", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLabelColor",1291,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"U 'TGLabel' - 0 - label k - 'Pixel_t' 0 - fore "
"k - 'Pixel_t' 0 - back", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BuildActelDisplay",1711,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 8, 1, 4, 0, 
"U 'TGCompositeFrame' - 0 - hframe U 'TGTextButton' - 2 - button1 "
"U 'TGTextButton' - 2 - button2 U 'TGComboBox' - 2 - combo "
"U 'TGLabel' - 2 - label1 U 'TGLabel' - 2 - label2 "
"i - 'Int_t' 0 - page C - 'Char_t' 10 - type", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SlowGui",714,G__slowguiDict_783_0_7, 105, G__get_linked_tagnum(&G__slowguiDictLN_SlowGui), -1, 0, 6, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h i - - 0 - tcrate "
"h - - 0 - jinfaddr i - - 0 - port", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateTpsfe",1110,G__slowguiDict_783_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'AMSWcom' - 0 - node r - 'ushort' 0 - amswaddr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateS9011ATFrame",1522,G__slowguiDict_783_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateTBSFrame",1320,G__slowguiDict_783_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateTpsfeFrame",1601,G__slowguiDict_783_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckTab",757,G__slowguiDict_783_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - val C - 'Char_t' 0 - FrameName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Exit",410,G__slowguiDict_783_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckSlowControl",1636,G__slowguiDict_783_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillTpsfePage",1286,G__slowguiDict_783_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - page", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TPSFEtoTDR",847,G__slowguiDict_783_0_16, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - tpsfe i - 'Int_t' 0 - tdr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ControlTpsfe",1251,G__slowguiDict_783_0_17, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - Mode i - 'Int_t' 0 - Tpsfe "
"i - 'Int_t' 0 - Tdr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTpsfeStatus",1446,G__slowguiDict_783_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - tpsfe", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTpsfeTrips",1332,G__slowguiDict_783_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tpsfe", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchTpsfeTdr",1438,G__slowguiDict_783_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - Tpsfe i - 'Int_t' 0 - Tdr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchTpsfeLrs",1445,G__slowguiDict_783_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - Tpsfe i - 'Int_t' 0 - Tdr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchTpsfeLrk",1437,G__slowguiDict_783_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - Tpsfe i - 'Int_t' 0 - Tdr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchTpsfeAll",1421,G__slowguiDict_783_0_23, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - Tpsfe i - 'Int_t' 0 - Tdr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchTpsfeTdrAll",1719,G__slowguiDict_783_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tpsfe", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchTpsfeLrsAll",1726,G__slowguiDict_783_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tpsfe", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchTpsfeLrkAll",1718,G__slowguiDict_783_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tpsfe", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchTpsfeAllAll",1702,G__slowguiDict_783_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tpsfe", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckMainTab",1146,G__slowguiDict_783_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckTpsfeClickDockable",2267,G__slowguiDict_783_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "U 'Event_t' - 0 - event", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateSettingsFrame",1936,G__slowguiDict_783_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SelectCommunicationMode",2363,G__slowguiDict_783_0_31, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - mode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SelectCommunicationPort",2395,G__slowguiDict_783_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - port", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ApplyAMSWire",1150,G__slowguiDict_783_0_33, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillTbsPage",1069,G__slowguiDict_783_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - page", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateTbs",893,G__slowguiDict_783_0_35, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'AMSWcom' - 0 - node r - 'ushort' 0 - amswaddr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTbsStatus",1229,G__slowguiDict_783_0_36, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tbs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckTbsClickDockable",2050,G__slowguiDict_783_0_37, 121, -1, -1, 0, 1, 1, 1, 0, "U 'Event_t' - 0 - event", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckTbsUndock",1387,G__slowguiDict_783_0_38, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckTbsDock",1160,G__slowguiDict_783_0_39, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ControlTbsVoltage",1756,G__slowguiDict_783_0_40, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - tbs i - 'Int_t' 0 - group "
"i - 'Int_t' 0 - voltage", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DisplayTbsStatus",1667,G__slowguiDict_783_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tbs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowBrotherTrip",1558,G__slowguiDict_783_0_42, 121, -1, -1, 0, 1, 1, 1, 0, "U 'SlowControl' - 0 - slowctl", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowPowerOn",1131,G__slowguiDict_783_0_43, 121, -1, -1, 0, 1, 1, 1, 0, "U 'SlowControl' - 0 - slowctl", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SelectActel",1097,G__slowguiDict_783_0_44, 121, -1, -1, 0, 3, 1, 1, 0, 
"i 'sACTEL' - 0 - Actel i - 'Int_t' 0 - ID "
"C - 'Char_t' 0 - type", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchActel",1115,G__slowguiDict_783_0_45, 121, -1, -1, 0, 3, 1, 1, 0, 
"i 'sACTEL' - 0 - Actel i - 'Int_t' 0 - ID "
"C - 'Char_t' 0 - type", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateS9011AT",1031,G__slowguiDict_783_0_46, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'AMSWcom' - 0 - node r - 'ushort' 0 - amswaddr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateS9051Page",1267,G__slowguiDict_783_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateS9053Page",1269,G__slowguiDict_783_0_48, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateS9055Page",1271,G__slowguiDict_783_0_49, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateTripIndicator",1936,G__slowguiDict_783_0_50, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame U 'TGLabel' - 2 - triplabel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreatePowerOnIndicator",2235,G__slowguiDict_783_0_51, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame U 'TGLabel' - 2 - pwonlabel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowTripIndicator",1757,G__slowguiDict_783_0_52, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGLabel' - 0 - alabel i - 'Int_t' 0 - show", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowPowerOnIndicator",2056,G__slowguiDict_783_0_53, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGLabel' - 0 - alabel i - 'Int_t' 0 - show", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateTextButton",1653,G__slowguiDict_783_0_54, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame U 'TGTextButton' - 2 - button "
"C - 'Char_t' 10 - text", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DisplayHelp",1119,G__slowguiDict_783_0_55, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Char_t' 0 - help", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateHelpButton",1625,G__slowguiDict_783_0_56, 85, G__get_linked_tagnum(&G__slowguiDictLN_TGPictureButton), -1, 0, 2, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - hmain C - 'Char_t' 10 - item", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateRefreshButton",1951,G__slowguiDict_783_0_57, 85, G__get_linked_tagnum(&G__slowguiDictLN_TGPictureButton), -1, 0, 2, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - hmain C - 'Char_t' 10 - item", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateInitLecroyButton",2258,G__slowguiDict_783_0_58, 85, G__get_linked_tagnum(&G__slowguiDictLN_TGPictureButton), -1, 0, 3, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - hmain C - 'Char_t' 10 - item "
"i - 'Int_t' 0 - val2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTbsADCBiasVoltage",1890,G__slowguiDict_783_0_59, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - Tbs i - 'Int_t' 0 - group "
"i - 'Int_t' 0 - update", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ControlTbsLr",1224,G__slowguiDict_783_0_60, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - Tbs i - 'Int_t' 0 - group "
"i - 'Int_t' 0 - lr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTbsBiasVoltage",2013,G__slowguiDict_783_0_61, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - Tbs r - 'ushort' 0 - group "
"i - 'Int_t' 0 '0' empty", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTbsBiasCurrent",2030,G__slowguiDict_783_0_62, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - Tbs r - 'ushort' 0 - Tdr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTbsBiasCurrents",2145,G__slowguiDict_783_0_63, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - Tbs i - 'Int_t' 0 '0' empty", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTbsADCBiasCurrent",1907,G__slowguiDict_783_0_64, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - Tbs r - 'ushort' 0 - Tdr "
"i - 'Int_t' 0 - update", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTbsADCBiasCurrents",2022,G__slowguiDict_783_0_65, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - Tbs i - 'Int_t' 0 - update", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LightColor",1015,G__slowguiDict_783_0_66, 107, -1, G__defined_typename("Pixel_t"), 0, 1, 1, 1, 0, "k - 'Pixel_t' 0 - color", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowTpsfeTrips",1461,G__slowguiDict_783_0_67, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - Tpsfe i - 'Int_t' 0 '0' empty", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ADCtoVolt",848,G__slowguiDict_783_0_68, 102, -1, G__defined_typename("Float_t"), 0, 3, 1, 1, 0, 
"r - 'ushort' 0 - adc r - 'ushort' 0 - group "
"r - 'ushort' 0 - cold", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ADCtoCurrent",1166,G__slowguiDict_783_0_69, 102, -1, G__defined_typename("Float_t"), 0, 4, 1, 1, 0, 
"r - 'ushort' 0 - adc r - 'ushort' 0 - Tbs "
"r - 'ushort' 0 - Tdr i - 'Int_t' 0 - correct", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowTbsEmpty",1241,G__slowguiDict_783_0_70, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tbs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DisplayTpsfeStatus",1884,G__slowguiDict_783_0_71, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tpsfe", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetS9011atStatus",1431,G__slowguiDict_783_0_72, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DisplayS9011atStatus",1869,G__slowguiDict_783_0_73, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowTpsfeEmpty",1458,G__slowguiDict_783_0_74, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tpsfe", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ControlS9051",1027,G__slowguiDict_783_0_75, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - group i - 'Int_t' 0 - side", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ControlS9053",1029,G__slowguiDict_783_0_76, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - group i - 'Int_t' 0 - side", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ControlS9055",1031,G__slowguiDict_783_0_77, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - group i - 'Int_t' 0 - side", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SelectADCmode",1229,G__slowguiDict_783_0_78, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - mode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowS9011atEmpty",1443,G__slowguiDict_783_0_79, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateOvercurrentIndicator",2704,G__slowguiDict_783_0_80, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - frame U 'TGLabel' - 2 - overlabel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowOvercurrentIndicator",2525,G__slowguiDict_783_0_81, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGLabel' - 0 - alabel i - 'Int_t' 0 - show", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalibrateADCCurrent",1842,G__slowguiDict_783_0_82, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - Tbs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadADCCurrentCalib",1794,G__slowguiDict_783_0_83, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreatePlotFrame",1502,G__slowguiDict_783_0_84, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreatePlot",1011,G__slowguiDict_783_0_85, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NewCanvas",902,G__slowguiDict_783_0_86, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - x i - 'Int_t' 0 - y "
"C - 'Char_t' 10 '\"\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateTDRPlotPage",1626,G__slowguiDict_783_0_87, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateCanvases",1431,G__slowguiDict_783_0_88, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RefreshCanvas",1323,G__slowguiDict_783_0_89, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TCanvas' - 0 - aCanvas", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitGraphs",1017,G__slowguiDict_783_0_90, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillGraphs",1004,G__slowguiDict_783_0_91, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OpenDataFile",1164,G__slowguiDict_783_0_92, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - crate", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseDataFile",1264,G__slowguiDict_783_0_93, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetButtonColor",1447,G__slowguiDict_783_0_94, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TGTextButton' - 0 - button k - 'Pixel_t' 0 - fore "
"k - 'Pixel_t' 0 - back", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetS9011DCDCButton",1492,G__slowguiDict_783_0_95, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - over i - 'Int_t' 0 - mode "
"U 'TGTextButton' - 0 - button", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SwitchAutoMode",1424,G__slowguiDict_783_0_96, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - Tpsfe C - 'Char_t' 0 - type", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitLecroy",1026,G__slowguiDict_783_0_97, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - val1 i - 'Int_t' 0 - val2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TrackerMonitor",1460,G__slowguiDict_783_0_98, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ProcessCanvas",1339,G__slowguiDict_783_0_99, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TVirtualPad' - 0 - pad U 'TObject' - 0 - obj "
"i - 'Int_t' 0 - event", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateZoomCanvases",1852,G__slowguiDict_783_0_100, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitGraph",902,G__slowguiDict_783_0_101, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - pwg i - - 0 - pwgpos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillTKGraph",1048,G__slowguiDict_783_0_102, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - pwg i - - 0 - pwgpos "
"d - - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateCurrent2",1400,G__slowguiDict_783_0_103, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - pwg i - - 0 - pwgpos "
"d - - 0 - current", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RefreshCanvas",1323,G__slowguiDict_783_0_104, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - pwg i - - 0 - pwgpos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTKTrips",1300,G__slowguiDict_783_0_105, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - pwg i - - 0 - pwgpos "
"i - - 0 - typ i - - 0 - cnt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DisplayTKVoltages",1722,G__slowguiDict_783_0_106, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - pwg d - - 0 - voltage", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTKBiasVoltage",1875,G__slowguiDict_783_0_107, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - Tbs r - 'ushort' 0 - group "
"i - - 0 - cold", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RefreshAll",1000,G__slowguiDict_783_0_108, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitCorrCurrent",1549,G__slowguiDict_783_0_109, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTKTPSFE",1156,G__slowguiDict_783_0_110, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - pwg i - - 0 - pwgpos "
"i - - 0 - typ i - - 0 - on", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EnableS9053",875,G__slowguiDict_783_0_111, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TestAMSW",728,G__slowguiDict_783_0_112, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - addr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimerDelay",1308,G__slowguiDict_783_0_113, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - val", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("SlowGui", 714, G__slowguiDict_783_0_114, (int) ('i'), G__get_linked_tagnum(&G__slowguiDictLN_SlowGui), -1, 0, 1, 1, 1, 0, "u 'SlowGui' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SlowGui", 840, G__slowguiDict_783_0_115, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__slowguiDict_783_0_116, (int) ('u'), G__get_linked_tagnum(&G__slowguiDictLN_SlowGui), -1, 1, 1, 1, 1, 0, "u 'SlowGui' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncslowguiDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalslowguiDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcslowguiDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__slowguiDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_Event_t = { "Event_t" , 115 , -1 };
G__linked_taginfo G__slowguiDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGLayoutHints = { "TGLayoutHints" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__slowguiDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGHorizontalFrame = { "TGHorizontalFrame" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TVirtualPad = { "TVirtualPad" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGTab = { "TGTab" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGPictureButton = { "TGPictureButton" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGDockableFrame = { "TGDockableFrame" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGHProgressBar = { "TGHProgressBar" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TGStatusBar = { "TGStatusBar" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_sVOLT = { "sVOLT" , 101 , -1 };
G__linked_taginfo G__slowguiDictLN_sACTEL = { "sACTEL" , 101 , -1 };
G__linked_taginfo G__slowguiDictLN_sActelMode = { "sActelMode" , 101 , -1 };
G__linked_taginfo G__slowguiDictLN_sDCDC = { "sDCDC" , 101 , -1 };
G__linked_taginfo G__slowguiDictLN_TrackerLadders = { "TrackerLadders" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TPSFE = { "TPSFE" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_TBS = { "TBS" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_AMSWcom = { "AMSWcom" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_SlowControl = { "SlowControl" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_S9011AT = { "S9011AT" , 99 , -1 };
G__linked_taginfo G__slowguiDictLN_SlowGui = { "SlowGui" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableslowguiDict() {
  G__slowguiDictLN_TObject.tagnum = -1 ;
  G__slowguiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__slowguiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__slowguiDictLN_TTimer.tagnum = -1 ;
  G__slowguiDictLN_Event_t.tagnum = -1 ;
  G__slowguiDictLN_TGWindow.tagnum = -1 ;
  G__slowguiDictLN_TGCompositeFrame.tagnum = -1 ;
  G__slowguiDictLN_TGLayoutHints.tagnum = -1 ;
  G__slowguiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__slowguiDictLN_TGTextButton.tagnum = -1 ;
  G__slowguiDictLN_TGHorizontalFrame.tagnum = -1 ;
  G__slowguiDictLN_TGMainFrame.tagnum = -1 ;
  G__slowguiDictLN_TFile.tagnum = -1 ;
  G__slowguiDictLN_TCanvas.tagnum = -1 ;
  G__slowguiDictLN_TVirtualPad.tagnum = -1 ;
  G__slowguiDictLN_TGTab.tagnum = -1 ;
  G__slowguiDictLN_TGLabel.tagnum = -1 ;
  G__slowguiDictLN_TGPictureButton.tagnum = -1 ;
  G__slowguiDictLN_TGCheckButton.tagnum = -1 ;
  G__slowguiDictLN_TGComboBox.tagnum = -1 ;
  G__slowguiDictLN_TGDockableFrame.tagnum = -1 ;
  G__slowguiDictLN_TGNumberEntry.tagnum = -1 ;
  G__slowguiDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__slowguiDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__slowguiDictLN_TGraph.tagnum = -1 ;
  G__slowguiDictLN_TTree.tagnum = -1 ;
  G__slowguiDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__slowguiDictLN_TGHProgressBar.tagnum = -1 ;
  G__slowguiDictLN_TGStatusBar.tagnum = -1 ;
  G__slowguiDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__slowguiDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__slowguiDictLN_sVOLT.tagnum = -1 ;
  G__slowguiDictLN_sACTEL.tagnum = -1 ;
  G__slowguiDictLN_sActelMode.tagnum = -1 ;
  G__slowguiDictLN_sDCDC.tagnum = -1 ;
  G__slowguiDictLN_TrackerLadders.tagnum = -1 ;
  G__slowguiDictLN_TPSFE.tagnum = -1 ;
  G__slowguiDictLN_TBS.tagnum = -1 ;
  G__slowguiDictLN_AMSWcom.tagnum = -1 ;
  G__slowguiDictLN_SlowControl.tagnum = -1 ;
  G__slowguiDictLN_S9011AT.tagnum = -1 ;
  G__slowguiDictLN_SlowGui.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableslowguiDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TTimer);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_Event_t);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGLayoutHints);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGHorizontalFrame);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TVirtualPad);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGTab);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGPictureButton);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGDockableFrame);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGraph);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGHProgressBar);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TGStatusBar);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_sVOLT);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_sACTEL);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_sActelMode);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_sDCDC);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TrackerLadders);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TPSFE);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_TBS);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_AMSWcom);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_SlowControl);
   G__get_linked_tagnum_fwd(&G__slowguiDictLN_S9011AT);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__slowguiDictLN_SlowGui),sizeof(SlowGui),-1,33792,(char*)NULL,G__setup_memvarSlowGui,G__setup_memfuncSlowGui);
}
extern "C" void G__cpp_setupslowguiDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupslowguiDict()");
  G__set_cpp_environmentslowguiDict();
  G__cpp_setup_tagtableslowguiDict();

  G__cpp_setup_inheritanceslowguiDict();

  G__cpp_setup_typetableslowguiDict();

  G__cpp_setup_memvarslowguiDict();

  G__cpp_setup_memfuncslowguiDict();
  G__cpp_setup_globalslowguiDict();
  G__cpp_setup_funcslowguiDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncslowguiDict();
  return;
}
class G__cpp_setup_initslowguiDict {
  public:
    G__cpp_setup_initslowguiDict() { G__add_setup_func("slowguiDict",(G__incsetup)(&G__cpp_setupslowguiDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initslowguiDict() { G__remove_setup_func("slowguiDict"); }
};
G__cpp_setup_initslowguiDict G__cpp_setup_initializerslowguiDict;

