#!/bin/bash

echo "Usage: $0 MM NN OO ..."
echo "       where MM, NN, OO, ... are the numbers of the crates to be considered into acquisition"
echo "--------------------------------------------------------------------------------------------"
echo "       alternatively you can type"
echo "       $0 standard"
echo "       to activate all JINF-T crates"

echo ""
echo "Removing all precedent configuration files..."
rm -f JINJ.conf
rm -f JLV1.conf
for ((crate=0; crate < 24; crate++))
do
	    stringa=$(printf "rm -f ./JINF_%02d.conf" $crate)
	    $stringa
done

echo "DataPath: ./Data/" > JINJ.conf
echo "CalPath: ./Calibrations/" >> JINJ.conf
echo "JINJflash: 3982"  >> JINJ.conf
echo "#SLAVE:    FLAG:    DAQ_MODE:   CONF_FILE:"  >> JINJ.conf

list=""

if (( $# < 1 ))
then
    echo "Using the standard configuration file for JINJ-00!"
    list="0 1 3 9 16 17 22 23"
    nparams="8"
else
    if [[ $1 = "standard" ]]
    then
	echo "Using the standard configuration file for JINJ-00!"
	list="0 1 3 9 16 17 22 23"
	nparams="8"
    else
	templist="$@"
	for param in $templist


	do
	    if [[ $param = "3" ]]
	    then
		crate="1"
	    elif [[ $param = "2" ]]
	    then
		crate="0"
	    elif [[ $param = "7" ]]
	    then
		crate="23"
	    elif [[ $param = "6" ]]
	    then
		crate="22"
	    elif [[ $param = "0" ]]
	    then
		crate="3"
	    elif [[ $param = "1" ]]
	    then
		crate="9"
	    elif [[ $param = "4" ]]
	    then
		crate="16"
	    elif [[ $param = "5" ]]
	    then
		crate="17"
	    fi
	    list="${list} ${crate}"
#	    echo $list
	done
	nparams="$#"
    fi
fi

#echo "$list"
#echo "$nparams"

counter=0

for ((crate=0; crate < 24; crate++))
do
    let "counter = 0"
    jlv1crate=14
    for parameter in $list
    do
	let "counter = $counter + 1"
#	echo $crate - $parameter - $counter
	if (( $crate == $parameter ))
	then
	    printf "%02d          1          1        JINF_%02d.conf\n" $crate $crate >> JINJ.conf
	    stringa=$(printf "ln -s ./ConfFiles/JINF_00.conf.bkp ./JINF_%02d.conf" $crate)
	    $stringa
	    echo $stringa
	    let " counter = 100"
	elif (( $crate == $jlv1crate ))
#	    echo $counter $nparams
	then
	    if (( $counter <= $nparams ))
	    then
		echo "14          1          1        JLV1.conf"  >> JINJ.conf
		stringa=$(printf "ln -s ./ConfFiles/JLV1.conf.bkp ./JLV1.conf")
		$stringa
		echo $stringa
		let " counter = 100"
	    fi
	elif (( $counter == $nparams ))
	then
	    printf "%02d          0          1        JINF_XX.conf\n" $crate >> JINJ.conf
	fi
    done
done

echo "the file ./JINJ.conf was created"

