*  $Id: trdf.h,v 1.1 2008/07/30 16:53:58 zuccon Exp $
        COMMON /DNDE  / NWE,WE(200),ANL(200,21),GAME(21)
        integer nwe
        real we,anl,game
        COMMON /TRDATA/ TDATA(10,4),WT(30),AMUTT(30,4)
        real tdata,wt,amutt
        COMMON /ITRD  / FOIL,GAS,GINWM(20),DNM(81,20),WTR(81)
        real foil,gas,ginwm,dnm,wtr
        COMMON /SYNTAB/ YTSYN(54),FTSYN(53)
        real ytsyn,ftsyn
        COMMON /CLION / NCLESTEP,CLESTEP(2,4000)
        integer nclestep
        real clestep
        COMMON /CSPTRD / SPTRD(100,4000,8)
        real sptrd


#undef  CERNLIB_GEANT321_GCTRAK_INC
#undef  CERNLIB_GEANT321_GTTRAK_INC
#undef  CERNLIB_GEANT321_GCKINE_INC
#undef  CERNLIB_GEANT321_GTKINE_INC
#undef  CERNLIB_GEANT321_GCFLAG_INC
#undef  CERNLIB_GEANT321_GTFLAG_INC
#undef  CERNLIB_GEANT321_GCVOLU_INC
#undef  CERNLIB_GEANT321_GTVOLU_INC
#undef  CERNLIB_GEANT321_GCTMED_INC
#undef  CERNLIB_GEANT321_GTTMED_INC
#undef  CERNLIB_GEANT321_GCBANK_INC
#undef  CERNLIB_GEANT321_GTBANK_INC
#undef  CERNLIB_GEANT321_GCKING_INC
#undef  CERNLIB_GEANT321_GTKING_INC
#undef  CERNLIB_GEANT321_GCSETS_INC
#undef  CERNLIB_GEANT321_GTSETS_INC
#undef  CERNLIB_GEANT321_GCONST_INC
#undef  CERNLIB_GEANT321_GCNUM_INC
#undef  CERNLIB_GEANT321_GTNUM_INC
#undef  CERNLIB_GEANT321_GCLIST_INC
#undef  CERNLIB_GEANT321_GTLIST_INC
#undef  CERNLIB_GEANT321_GCLINK_INC
#undef  CERNLIB_GEANT321_GTLINK_INC
#undef  CERNLIB_GEANT321_GCCUTS_INC
#undef  CERNLIB_GEANT321_GTCUTS_INC
#undef  CERNLIB_GEANT321_GCKMAX_INC
#undef  CERNLIB_GEANT321_GTKMAX_INC





