*  $Id: trfitcl.h,v 1.1.1.1 2007/11/13 09:56:10 zuccon Exp $
      COMMON /TFITRE/ PHIV,XATV,YATV,ZATV,
     $                IHATS,PHIS,XATS,YATS,ZATS,SPVER,SPLEN,
     $                CHARGE,PPRINV,PINV,XCEN,YCEN,
     $                CHIXY,NDFXY,CHIZ,NDFZ,ZSPAR,ZOPAR,ZSESQ,ZOESQ,
     $                NOXYZ,S2XOYS,S2XOYV,
     $                S2PPRI,S2PHIS,S2PHIV,COVPRS,COVPRV
      COMMON /TCIRCL/  XR,YR,PHI,DC,DI,COVDPD(6),SINF,COSF,SIGNR,XS,YS,
     $                 A,B,RO,R,COVPHR(3),IGF,IGL,NGOOD,CHITR
      COMMON /TFITVX/  IFVER,XVER,YVER,ZVER,XVERR,YVERR,ZVERR
      COMMON /TFITCD/  BTFIEL,TPARAM(20),TPERR(20)
C
C-- COMMON BLOCK FOR TRACK FITTING INTERFACE, P=TRFIT, D=TRAFIT.
C
C  BTFIEL   BZ FIELD VALUE IN TESLA             (IN)
C
C  TPARAM:  RESULTS FROM THE TRACK FIT          (OUT)
C
C     1     TRACK IDENTIFIER
C     2
C     3
C     4     TRACK LENGTH IN SPACE
C     5     NUMBER OF POINTS USED IN XY-FIT
C     6     TRACK POSITION X-COORDINATE
C     7     TRACK POSITION Y-COORDINATE
C     8     TRACK POSITION Z-COORDINATE
C     9     TRACK CHARGE DIVIDED BY TRACK MOMENTUM,  Q/P
C    10     TRACK DIP ANGLE = TRACK ANGLE FROM XY-PLANE = 90DEG-THETA
C    11     TRACK PHI ANGLE = AZIMUTH AROUND Z-AXIS
C    12     TRACK PHI ANGLE = AZIMUTH AROUND Z-AXIS, AT VERTEX
C    13     TRACK POSITION X-COORDINATE AT VERTEX
C    14     TRACK POSITION Y-COORDINATE AT VERTEX
C    15     TRACK POSITION Z-COORDINATE AT VERTEX
C
C  TPERR:    RESULTS FROM THE TRACK FIT, ERRORS ETC.    (OUT)
C
C     1     CHIZ,   RESIDUAL SUM OF SQUARES FROM SZ-FIT
C     2     NDFZ,   NUMBER OF DEGREES OF FREEDOM IN SZ-FIT
C     3     NPARSZ, NUMBER OF PARAMETERS IN SZ-FIT
C     4     NOXYZ,  FREE START COORDINATE IN XY-FIT ( 1=X, 2=Y )
C     5     S2XOYV, VARIANCE OF START COORDINATE IN XY-FIT, AT VERTEX
C     6     S2ZAV,  VARIANCE OF Z-COORDINATE IN SZ-FIT, AT VERTEX
C     7     S2PINV, VARIANCE OF INVERSE MOMENTUM, 1/P
C     8     S2DIP,  VARIANCE OF DIP ANGLE
C     9     S2PHIV, VARIANCE OF PHI ANGLE, AT VERTEX
C    10     .....   COVARIANCE OF 1/P AND PHI, AT VERTEX
C    11     CHIXY,  RESIDUAL SUM OF SQUARES FROM XY-FIT
C    12     NDFXY,  NUMBER OF DEGREES OF FREEDOM IN XY-FIT
C    13     NPARXY, NUMBER OF PARAMETERS IN XY-FIT ( 2=LINE, 3=CIRCLE )
C    14     S2PHIS, VARIANCE OF PHI ANGLE, AT FIRST POINT
C    15     S2XOYS, VARIANCE OF START COORDINATE IN XY-FIT, AT FIRST PT
C    16     S2ZAS,  VARIANCE OF Z-COORDINATE IN SZ-FIT, AT FIRST POINT
C    17     .....   COVARIANCE OF 1/P AND PHI, AT FIRST POINT
C
C--------------------------------------------------------------------012
