*  $Id: every.f,v 1.1.1.1 2007/11/13 09:56:10 zuccon Exp $
      REAL FUNCTION every()
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      1    
*     Ntuple Title:   AMS Ntuple
*     Creation:       15/05/98 19.43.07
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER         IDNEVT,NCHEVT,ICHEVT
      REAL            OBS(13)
*
      COMMON /PAWIDN/ IDNEVT,OBS
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL GrMedPhi,RadS,ThetaS,PhiS,YawS,PitchS,RollS,VelocityS
     + ,beta(100),betaerror(100),betachi2(100),betachi2s(100)
     + ,probtof(7,10),probtracker(7,10),pmass(10),perrmass(10),pmom(10)
     + ,perrmom(10),pcharge(10),ptheta(10),pphi(10),pcoo(3,10)
     + ,signalctc(2,10),betactc(2,10),errorbetactc(2,10),cooctc(3,2,10)
     + ,cootof(3,4,10),cooanti(3,2,10),cootr(3,6,10),TOFEdep(20)
     + ,TOFTime(20),TOFETime(20),TOFCoo(3,20),TOFErCoo(3,20)
     + ,TOFMCXcoo(3,200),TOFMCtof(200),TOFMCedep(200),Sumt(200)
     + ,Sigmat(200),Meant(200),RMSt(200),ErrorMeant(200)
     + ,Amplitude(5,200),ss(5,2,200),xca(3,200),xcb(3,200),xgl(3,200)
     + ,summc(200),hitr(3,500),ehitr(3,500),sumr(500),difosum(500)
     + ,Chi2StrLine(20),Chi2Circle(20),CircleRidgidity(20)
     + ,Chi2FastFit(20),Ridgidity(20),ErrRidgidity(20),Theta(20),phi(20)
     + ,p0(3,20),gchi2(20),gridgidity(20),gerrridgidity(20),gtheta(20)
     + ,gphi(20),gp0(3,20),hchi2(2,20),HRidgidity(2,20)
     + ,HErrRidgidity(2,20),htheta(2,20),hphi(2,20),hp0(3,2,20)
     + ,fchi2ms(20),gchi2ms(20),ridgidityms(20),gridgidityms(20)
     + ,coo(3,20),dir(3,20),momentum(20),mass(20),charge(20)
     + ,ctccoo(3,20)
      INTEGER eventno,run,runtype,time(2),RawWords,Particles,Tracks
     + ,Betas,Charges,TrRecHits,TrClusters,TrRawClusters,TrMCClusters
     + ,TOFClusters,TOFMCClusters,CTCClusters,CTCMCClusters
     + ,AntiMCClusters,AntiClusters,nbeta,betastatus(100)
     + ,betapattern(100),betantof(100),betaptof(4,100),betaptr(100)
     + ,ncharge,chargestatus(10),chargebetap(10),chargetof(10)
     + ,chargetracker(10),npart,pctcp(2,10),pbetap(10),pchargep(10)
     + ,ptrackp(10),pid(10),ntof,TOFStatus(20),plane(20),bar(20),ntofmc
     + ,TOFMCIdsoft(200),Ntrcl,Idsoft(200),Statust(200),NelemL(200)
     + ,NelemR(200),ntrclmc,IdsoftMC(200),Itra(200),Left(2,200)
     + ,Center(2,200),Right(2,200),ntrrh,px(500),py(500),statusr(500)
     + ,Layer(500),ntrtr,trstatus(20),pattern(20),nhits(20),phits(6,20)
     + ,FastFitDone(20),GeaneFitDone(20),AdvancedFitDone(20),nmcg
     + ,nskip(20),Particle(20),nctccl,CTCStatus(20),CTCLayer(20)
     + ,nctcclmc,CTCMCIdsoft(200),nanti,AntiStatus(16),AntiSector(16)
     + ,nantimc,AntiMCIdsoft(200),nlvl3,LVL3TOFTr(2),LVL3AntiTr(2)
     + ,LVL3TrackerTr(2),LVL3NTrHits(2),LVL3NPat(2),LVL3Pattern(2,2)
     + ,nlvl1,LVL1Mode(2),LVL1Flag(2),LVL1TOFPatt(4,2),LVL1TOFPatt1(4,2)
     + ,LVL1AntiPatt(2)
      REAL ctcercoo(3,20),ctcrawsignal(20),ctcsignal(20),ctcesignal(20)
     + ,CTCMCXcoo(3,200),CTCMCXdir(3,200),CTCstep(200),ctccharge(200)
     + ,ctcbeta(200),ctcedep(200),AntiEdep(16),AntiCoo(3,16)
     + ,AntiErCoo(3,16),AntiMCXcoo(3,200),AntiMCtof(200),AntiMCedep(200)
     + ,LVL3Residual(2,2),LVL3Time(2),LVL3ELoss(2),ctchitsignal(50)
     + ,s2n(500),antirawsignal(32),tofrtovta(2,20),tofrtovtd(2,20)
     + ,tofrsdtm(2,20)
      INTEGER nctcht,CTChitStatus(50),CTChitLayer(50),ctchitcolumn(50)
     + ,ctchitrow(50),ntrraw,rawaddress(500),rawlength(500),nantiraw
     + ,antirawstatus(32),antirawsector(32),antirawupdown(32),ntofraw
     + ,tofrstatus(20),tofrplane(20),tofrbar(20)
*
      COMMON /PAWCR4/ eventno,run,runtype,time,RawWords,GrMedPhi,RadS
     + ,ThetaS,PhiS,YawS,PitchS,RollS,VelocityS,Particles,Tracks,Betas
     + ,Charges,TrRecHits,TrClusters,TrRawClusters,TrMCClusters
     + ,TOFClusters,TOFMCClusters,CTCClusters,CTCMCClusters
     + ,AntiMCClusters,AntiClusters,nbeta,betastatus,betapattern,beta
     + ,betaerror,betachi2,betachi2s,betantof,betaptof,betaptr,ncharge
     + ,chargestatus,chargebetap,chargetof,chargetracker,probtof
     + ,probtracker,npart,pctcp,pbetap,pchargep,ptrackp,pid,pmass
     + ,perrmass,pmom,perrmom,pcharge,ptheta,pphi,pcoo,signalctc,betactc
     + ,errorbetactc,cooctc,cootof,cooanti,cootr,ntof,TOFStatus,plane
     + ,bar,TOFEdep,TOFTime,TOFETime,TOFCoo,TOFErCoo,ntofmc,TOFMCIdsoft
     + ,TOFMCXcoo,TOFMCtof,TOFMCedep,Ntrcl,Idsoft,Statust,NelemL,NelemR
     + ,Sumt,Sigmat,Meant,RMSt,ErrorMeant,Amplitude,ntrclmc,IdsoftMC
     + ,Itra,Left,Center,Right,ss,xca,xcb,xgl,summc,ntrrh,px,py,statusr
     + ,Layer,hitr,ehitr,sumr,difosum,ntrtr,trstatus,pattern,nhits,phits
     + ,FastFitDone,GeaneFitDone,AdvancedFitDone,Chi2StrLine,Chi2Circle
     + ,CircleRidgidity,Chi2FastFit,Ridgidity,ErrRidgidity,Theta,phi,p0
     + ,gchi2,gridgidity,gerrridgidity,gtheta,gphi,gp0,hchi2,HRidgidity
     + ,HErrRidgidity,htheta,hphi,hp0,fchi2ms,gchi2ms,ridgidityms
     + ,gridgidityms,nmcg,nskip,Particle,coo,dir,momentum,mass,charge
     + ,nctccl,CTCStatus,CTCLayer,ctccoo,ctcercoo,ctcrawsignal,ctcsignal
     + ,ctcesignal,nctcclmc,CTCMCIdsoft,CTCMCXcoo,CTCMCXdir,CTCstep
     + ,ctccharge,ctcbeta,ctcedep,nanti,AntiStatus,AntiSector,AntiEdep
     + ,AntiCoo,AntiErCoo,nantimc,AntiMCIdsoft,AntiMCXcoo,AntiMCtof
     + ,AntiMCedep,nlvl3,LVL3TOFTr,LVL3AntiTr,LVL3TrackerTr,LVL3NTrHits
     + ,LVL3NPat,LVL3Pattern,LVL3Residual,LVL3Time,LVL3ELoss,nlvl1
     + ,LVL1Mode,LVL1Flag,LVL1TOFPatt,LVL1TOFPatt1,LVL1AntiPatt,nctcht
     + ,CTChitStatus,CTChitLayer,ctchitcolumn,ctchitrow,ctchitsignal
     + ,ntrraw,rawaddress,rawlength,s2n,nantiraw,antirawstatus
     + ,antirawsector,antirawupdown,antirawsignal,ntofraw,tofrstatus
     + ,tofrplane,tofrbar,tofrtovta,tofrtovtd,tofrsdtm
*

*
*--   Enter user code here
*
        double precision a(3,3)
        logical cuts(10)
        data init/0/
        if(init.eq.0)then
          init=1
*
*  Charge one particle
*          
        call hbook1(101,'electrons mass',200,0.,1.,0.)
        call hbook1(201,'muons mass',200,0.,1.,0.)
        call hbook1(301,'protons mass',200,0.,2.,0.)
        call hbook1(401,'he mass',200,0.,8.,0.)
        call hbook1(501,'li mass',200,0.,12.,0.)
        call hbook1(601,'bo mass',200,0.,16.,0.)
        call hbook1(701,'be mass',200,0.,20.,0.)
        call hbook1(801,'c mass',200,0.,24.,0.)
        call hbook1(2801,'c mass',200,0.,36.,0.)
        call hbook1(2802,'c mass',200,0.,36.,0.)
        call hbook1(1101,'aelectrons mass',200,0.,1.,0.)
        call hbook1(1201,'amuons mass',200,0.,1.,0.)
        call hbook1(1301,'aprotons mass',200,0.,2.,0.)
        call hbook1(1401,'ahe mass',200,0.,8.,0.)
        call hbook1(1501,'ali mass',200,0.,12.,0.)
        call hbook1(1601,'abo mass',200,0.,16.,0.)
        call hbook1(1701,'abe mass',200,0.,20.,0.)
        call hbook1(1801,'ac mass',200,0.,24.,0.)
        call hbook1(77,'rr',200,-1.1,1.1,0.)         
        endif
        xx=0
        xx1=0
        xx2=0
        id=0
        do i=1,10
         cuts(i)=.false.
        enddo
        if(npart.gt.0)then
          xll=-58
          xlr=58
          yll=-38
          ylr=43
          cuts(2)=cooctc(1,1,1).gt.xll.and.
     +      cooctc(1,1,1).lt.xlr
          cuts(3)=cooctc(2,1,1).gt.yll.and.
     +      cooctc(2,1,1).lt.ylr
          do i=1,nctccl
            xx=xx+ctcrawsignal(i)
            if(ctclayer(i).eq.1)xx1=xx1+ctcrawsignal(i)
            if(ctclayer(i).eq.2)xx2=xx2+ctcrawsignal(i)
          enddo
          if(pmom(1).lt.0)iad=1000
          if(pmom(1).gt.0)iad=0
          ibeta=pbetap(1)
          itr=ptrackp(1)
          if(chi2circle(itr).lt.2.5.and.
     +    betachi2(ibeta).lt.2)then
            if(abs(pmom(1)).lt.0.4.and.abs(beta(ibeta)).gt.0.99.and.
     +        xx.gt.2)then
              id=100
            else if(cuts(2).and.cuts(3).and.xx.lt.1.and.
     +          beta(ibeta).lt.0.95)then
*
* Low beta stuff
*              
              if(pcharge(1).eq.1)then
                if(pmass(1).lt.0.5)then
                  id=200
                else 
                  id=300
                endif
              else  
               id=pcharge(1)*100+200       
              endif
            endif
            if(id.ne.0)then
              call hf1(id+iad+1,pmass(1),1.)
            endif
          endif
          if(beta(ibeta).gt.0.and.beta(ibeta).lt.0.9)then
           if(chargetracker(1).gt.2)then
             rmom=pmom(1)/pcharge(1)*chargetracker(1)
             gamma=sqrt(1-beta(ibeta)**2)
             pms=rmom/beta(ibeta)*gamma
             call hf1(2801,pms,1.)
             if(pcharge(1).gt.4.5)call hf1(2802,pmass(1),1.)
           endif
          endif  
        endif
        cy=cos(yaws)
        sy=sin(yaws)
        cr=cos(rolls)
        sr=sin(rolls)
        cp=cos(pitchs)
        sp=sin(pitchs)
        a(1,1)=cy*cp
        a(2,1)=-sy
        a(3,1)=cy*sp
        a(1,2)=cr*sy*cp-sr*sp
        a(2,2)=cr*cy
        a(3,2)=cr*sy*sp+sr*cp
        a(1,3)=-sr*sy*cp-cr*sp
        a(2,3)=-sr*cy
        a(3,3)=-sr*sy*sp+cr*cp
        cost=a(3,3)
c        do i=1,3
c          do j=1,3
c            s=0
c            do k=1,3
c             s=s+a(k,i)*a(k,j)
c            enddo
c            write(*,*)i,j,s
c          enddo
c        enddo
        call hf1(77,cost,1.)        
        every=0
*
      END
