*  $Id: ntuple.f,v 1.1.1.1 2007/11/13 09:56:10 zuccon Exp $
      REAL FUNCTION ntuple(XDUMMY)
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      1    
*     Ntuple Title:   Converted Ntuple
*     Creation:       17/10/96 20.42.24
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER         IDNEVT,NCHEVT,ICHEVT
      REAL            OBS(13)
*
      COMMON /PAWIDN/ IDNEVT,OBS
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      REAL beta(10),betaerror(10),betachi2(10),chargebetap(10)
     + ,probtof(7,10),probtracker(7,10),pmass(10),perrmass(10),pmom(10)
     + ,perrmom(10),pcharge(10),ptheta(10),pphi(10),pcoo(3,10),panti(10)
     + ,signalctc(10),betactc(10),errorbetactc(10),cooctc(3,10)
     + ,TOFEdep(20),TOFTime(20),TOFETime(20),TOFCoo(3,20),TOFErCoo(3,20)
     + ,TOFMCXcoo(3,200),TOFMCtof(200),TOFMCedep(200),Sumt(50)
     + ,Sigmat(50),Meant(50),RMSt(50),ErrorMeant(50),ss(5,2,200)
     + ,xca(3,200),xcb(3,200),xgl(3,200),summc(200),hitr(3,200)
     + ,ehitr(3,200),sumr(200),difosum(200),Chi2StrLine(20)
     + ,Chi2Circle(20),CircleRidgidity(20),Chi2FastFit(20),Ridgidity(20)
     + ,ErrRidgidity(20),Theta(20),phi(20),p0(3,20),gchi2(20)
     + ,gridgidity(20),gerrridgidity(20),gtheta(20),gphi(20),gp0(3,20)
     + ,hchi2(2,20),HRidgidity(2,20),HErrRidgidity(2,20),htheta(2,20)
     + ,hphi(2,20),hp0(3,2,20),fchi2ms(20),gchi2ms(20),ridgidityms(20)
     + ,gridgidityms(20),coo(3,20),dir(3,20),momentum(20),mass(20)
     + ,charge(20),CTCStatus(20),ctccoo(3,20),ctcercoo(3,20)
     + ,ctcrawsignal(20),ctcsignal(20),ctcesignal(20),CTCMCIdsoft(200)
     + ,CTCMCXcoo(3,200),CTCMCXdir(3,200),CTCstep(200),ctcedep(200)
     + ,ctcbeta(200)
      INTEGER eventno,run,runtype,time(2),nbeta,betapattern(10),ncharge
     + ,chargetof(10),chargetracker(10),npart,pbetap(10),pchargep(10)
     + ,ptrackp(10),pid(10),ntof,TOFStatus(20),plane(20),bar(20),ntofmc
     + ,TOFMCIdsoft(200),ntrcl,Idsoft(5,50),Statust(50),Nelemt(50)
     + ,ntrclmc,IdsoftMC(200),Itra(200),Left(2,200),Center(2,200)
     + ,Right(2,200),ntrrh,statusr(200),Layer(200),ntrtr,trstatus(20)
     + ,pattern(20),nhits(20),GeaneFitDone(20),AdvancedFitDone(20),nmcg
     + ,Particle(20),nctccl,nctcclmc
*
      COMMON /PAWCR4/ eventno,run,runtype,time,nbeta,betapattern,beta
     + ,betaerror,betachi2,ncharge,chargebetap,chargetof,chargetracker
     + ,probtof,probtracker,npart,pbetap,pchargep,ptrackp,pid,pmass
     + ,perrmass,pmom,perrmom,pcharge,ptheta,pphi,pcoo,panti,signalctc
     + ,betactc,errorbetactc,cooctc,ntof,TOFStatus,plane,bar,TOFEdep
     + ,TOFTime,TOFETime,TOFCoo,TOFErCoo,ntofmc,TOFMCIdsoft,TOFMCXcoo
     + ,TOFMCtof,TOFMCedep,ntrcl,Idsoft,Statust,Nelemt,Sumt,Sigmat,Meant
     + ,RMSt,ErrorMeant,ntrclmc,IdsoftMC,Itra,Left,Center,Right,ss,xca
     + ,xcb,xgl,summc,ntrrh,statusr,Layer,hitr,ehitr,sumr,difosum,ntrtr
     + ,trstatus,pattern,nhits,GeaneFitDone,AdvancedFitDone,Chi2StrLine
     + ,Chi2Circle,CircleRidgidity,Chi2FastFit,Ridgidity,ErrRidgidity
     + ,Theta,phi,p0,gchi2,gridgidity,gerrridgidity,gtheta,gphi,gp0
     + ,hchi2,HRidgidity,HErrRidgidity,htheta,hphi,hp0,fchi2ms,gchi2ms
     + ,ridgidityms,gridgidityms,nmcg,Particle,coo,dir,momentum,mass
     + ,charge,nctccl,CTCStatus,ctccoo,ctcercoo,ctcrawsignal,ctcsignal
     + ,ctcesignal,nctcclmc,CTCMCIdsoft,CTCMCXcoo,CTCMCXdir,CTCstep
     + ,ctcedep,ctcbeta
*

*
*--   Enter user code here
*

      ntuple = 1.
*
      END
