/********************************************************************
* CC/dictAMSBase.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CC/dictAMSBase.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtabledictAMSBase();
extern void G__cpp_setup_inheritancedictAMSBase();
extern void G__cpp_setup_typetabledictAMSBase();
extern void G__cpp_setup_memvardictAMSBase();
extern void G__cpp_setup_globaldictAMSBase();
extern void G__cpp_setup_memfuncdictAMSBase();
extern void G__cpp_setup_funcdictAMSBase();
extern void G__set_cpp_environmentdictAMSBase();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/apool.h"
#include "include/astring.h"
#include "include/cont.h"
#include "include/id.h"
#include "include/link.h"
#include "include/node.h"
#include "include/point.h"
#include "include/snode.h"
#include "include/upool.h"
#include "include/timeid.h"
#include "include/amsdbc.h"
#include "include/uzstat.h"
#include "include/amsgobj.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictAMSBaseLN_tm;
extern G__linked_taginfo G__dictAMSBaseLN_TClass;
extern G__linked_taginfo G__dictAMSBaseLN_TBuffer;
extern G__linked_taginfo G__dictAMSBaseLN_TMemberInspector;
extern G__linked_taginfo G__dictAMSBaseLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__dictAMSBaseLN_AMSID;
extern G__linked_taginfo G__dictAMSBaseLN_AMSIDi;
extern G__linked_taginfo G__dictAMSBaseLN_AMSIDs;
extern G__linked_taginfo G__dictAMSBaseLN_AString;
extern G__linked_taginfo G__dictAMSBaseLN_AStringcLcLData;
extern G__linked_taginfo G__dictAMSBaseLN_AMSNode;
extern G__linked_taginfo G__dictAMSBaseLN_AMSNodeMap;
extern G__linked_taginfo G__dictAMSBaseLN_AMSNodeMapError;
extern G__linked_taginfo G__dictAMSBaseLN_AMSlink;
extern G__linked_taginfo G__dictAMSBaseLN_AMSContainer;
extern G__linked_taginfo G__dictAMSBaseLN_AMSRotMat;
extern G__linked_taginfo G__dictAMSBaseLN_AMSPoint;
extern G__linked_taginfo G__dictAMSBaseLN_AMSDir;
extern G__linked_taginfo G__dictAMSBaseLN_dirent64;
extern G__linked_taginfo G__dictAMSBaseLN_AMSTimeID;
extern G__linked_taginfo G__dictAMSBaseLN_listlEAMSTimeIDcLcLiibecOallocatorlEAMSTimeIDcLcLiibegRsPgR;
extern G__linked_taginfo G__dictAMSBaseLN_listlEAMSTimeIDcLcLiibecOallocatorlEAMSTimeIDcLcLiibegRsPgRcLcLiterator;
extern G__linked_taginfo G__dictAMSBaseLN_AMSTimeIDcLcLCType;

/* STUB derived class for protected member access */
