   1:SEND COMMAND                  :CAN-02, C78, PS_ENA_DIS_PILOT_VALVES_RED_ENA.CMM, 0
   2:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
   3:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   4:SEND COMMAND                  :CAN-02, C7B, PS_OPEN_CLOSE_PILOT_VALVE_RED_V55_OPEN.CMM, 0
   5:SEND COMMAND                  :CAN-02, C05, CAB_GET_DIGITAL_STATUS_RED.CMM, 0
   6:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE
   7:SEND COMMAND                  :CAN-02, C03, CAB_GET_ESSENTIAL_STATUS.CMM, 0
   8:REQUEST MESSAGE               :GEP-05, This is a request message example, NONE