/********************************************************************
* slowgui2Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error slowgui2Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableslowgui2Dict();
extern void G__cpp_setup_inheritanceslowgui2Dict();
extern void G__cpp_setup_typetableslowgui2Dict();
extern void G__cpp_setup_memvarslowgui2Dict();
extern void G__cpp_setup_globalslowgui2Dict();
extern void G__cpp_setup_memfuncslowgui2Dict();
extern void G__cpp_setup_funcslowgui2Dict();
extern void G__set_cpp_environmentslowgui2Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "slowgui2.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__slowgui2DictLN_TObject;
extern G__linked_taginfo G__slowgui2DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__slowgui2DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__slowgui2DictLN_TTimer;
extern G__linked_taginfo G__slowgui2DictLN_Event_t;
extern G__linked_taginfo G__slowgui2DictLN_TGWindow;
extern G__linked_taginfo G__slowgui2DictLN_TGCompositeFrame;
extern G__linked_taginfo G__slowgui2DictLN_TGLayoutHints;
extern G__linked_taginfo G__slowgui2DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__slowgui2DictLN_TGTextButton;
extern G__linked_taginfo G__slowgui2DictLN_TGVerticalFrame;
extern G__linked_taginfo G__slowgui2DictLN_TGHorizontalFrame;
extern G__linked_taginfo G__slowgui2DictLN_TGMainFrame;
extern G__linked_taginfo G__slowgui2DictLN_TGGroupFrame;
extern G__linked_taginfo G__slowgui2DictLN_TFile;
extern G__linked_taginfo G__slowgui2DictLN_TCanvas;
extern G__linked_taginfo G__slowgui2DictLN_TVirtualPad;
extern G__linked_taginfo G__slowgui2DictLN_TGTab;
extern G__linked_taginfo G__slowgui2DictLN_TGLabel;
extern G__linked_taginfo G__slowgui2DictLN_TGPictureButton;
extern G__linked_taginfo G__slowgui2DictLN_TGCheckButton;
extern G__linked_taginfo G__slowgui2DictLN_TGComboBox;
extern G__linked_taginfo G__slowgui2DictLN_TGDockableFrame;
extern G__linked_taginfo G__slowgui2DictLN_TGNumberEntry;
extern G__linked_taginfo G__slowgui2DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__slowgui2DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__slowgui2DictLN_TGraph;
extern G__linked_taginfo G__slowgui2DictLN_TTree;
extern G__linked_taginfo G__slowgui2DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__slowgui2DictLN_TGHProgressBar;
extern G__linked_taginfo G__slowgui2DictLN_TGStatusBar;
extern G__linked_taginfo G__slowgui2DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__slowgui2DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__slowgui2DictLN_sVOLT;
extern G__linked_taginfo G__slowgui2DictLN_sDCDC;
extern G__linked_taginfo G__slowgui2DictLN_TrackerLadders;
extern G__linked_taginfo G__slowgui2DictLN_AMSWcom;
extern G__linked_taginfo G__slowgui2DictLN_SlowGui;

/* STUB derived class for protected member access */
