/********************************************************************
* slowguiDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error slowguiDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableslowguiDict();
extern void G__cpp_setup_inheritanceslowguiDict();
extern void G__cpp_setup_typetableslowguiDict();
extern void G__cpp_setup_memvarslowguiDict();
extern void G__cpp_setup_globalslowguiDict();
extern void G__cpp_setup_memfuncslowguiDict();
extern void G__cpp_setup_funcslowguiDict();
extern void G__set_cpp_environmentslowguiDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "slowgui.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__slowguiDictLN_TObject;
extern G__linked_taginfo G__slowguiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__slowguiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__slowguiDictLN_TTimer;
extern G__linked_taginfo G__slowguiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__slowguiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__slowguiDictLN_Event_t;
extern G__linked_taginfo G__slowguiDictLN_TGWindow;
extern G__linked_taginfo G__slowguiDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__slowguiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__slowguiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__slowguiDictLN_TGCompositeFrame;
extern G__linked_taginfo G__slowguiDictLN_TGLayoutHints;
extern G__linked_taginfo G__slowguiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__slowguiDictLN_TGTextButton;
extern G__linked_taginfo G__slowguiDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__slowguiDictLN_TGMainFrame;
extern G__linked_taginfo G__slowguiDictLN_TFile;
extern G__linked_taginfo G__slowguiDictLN_TCanvas;
extern G__linked_taginfo G__slowguiDictLN_TVirtualPad;
extern G__linked_taginfo G__slowguiDictLN_TGTab;
extern G__linked_taginfo G__slowguiDictLN_TGLabel;
extern G__linked_taginfo G__slowguiDictLN_TGPictureButton;
extern G__linked_taginfo G__slowguiDictLN_TGCheckButton;
extern G__linked_taginfo G__slowguiDictLN_TGComboBox;
extern G__linked_taginfo G__slowguiDictLN_TGDockableFrame;
extern G__linked_taginfo G__slowguiDictLN_TGNumberEntry;
extern G__linked_taginfo G__slowguiDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__slowguiDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__slowguiDictLN_TGraph;
extern G__linked_taginfo G__slowguiDictLN_TTree;
extern G__linked_taginfo G__slowguiDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__slowguiDictLN_TGHProgressBar;
extern G__linked_taginfo G__slowguiDictLN_TGStatusBar;
extern G__linked_taginfo G__slowguiDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__slowguiDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__slowguiDictLN_sVOLT;
extern G__linked_taginfo G__slowguiDictLN_sACTEL;
extern G__linked_taginfo G__slowguiDictLN_sActelMode;
extern G__linked_taginfo G__slowguiDictLN_sDCDC;
extern G__linked_taginfo G__slowguiDictLN_TrackerLadders;
extern G__linked_taginfo G__slowguiDictLN_TPSFE;
extern G__linked_taginfo G__slowguiDictLN_TBS;
extern G__linked_taginfo G__slowguiDictLN_AMSWcom;
extern G__linked_taginfo G__slowguiDictLN_SlowControl;
extern G__linked_taginfo G__slowguiDictLN_S9011AT;
extern G__linked_taginfo G__slowguiDictLN_SlowGui;

/* STUB derived class for protected member access */
