/********************************************************************
* rootElibdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootElibdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablerootElibdict();
extern void G__cpp_setup_inheritancerootElibdict();
extern void G__cpp_setup_typetablerootElibdict();
extern void G__cpp_setup_memvarrootElibdict();
extern void G__cpp_setup_globalrootElibdict();
extern void G__cpp_setup_memfuncrootElibdict();
extern void G__cpp_setup_funcrootElibdict();
extern void G__set_cpp_environmentrootElibdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Cluster.hh"
#include "Event.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootElibdictLN_TClass;
extern G__linked_taginfo G__rootElibdictLN_TBuffer;
extern G__linked_taginfo G__rootElibdictLN_TMemberInspector;
extern G__linked_taginfo G__rootElibdictLN_TObject;
extern G__linked_taginfo G__rootElibdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootElibdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootElibdictLN_TClonesArray;
extern G__linked_taginfo G__rootElibdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__rootElibdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootElibdictLN_Cluster;
extern G__linked_taginfo G__rootElibdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__rootElibdictLN_Event;
extern G__linked_taginfo G__rootElibdictLN_RHClass;

/* STUB derived class for protected member access */
